# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Auth/user_info.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseUserInfo(HttpRunner):

    config = (
        Config("获取用户信息")
        .variables(**{"access_token": "${get_token()}"})
        .export(*["customerId"])
    )

    teststeps = [
        Step(
            RunRequest("获取用户数据")
            .get("${ENV(api_url)}/users/info?")
            .with_headers(**{"authorization": "Bearer $access_token"})
            .extract()
            .with_jmespath("body.customerId", "customerId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.id", 4990)
            .assert_equal("body.authUserId", 1020993)
            .assert_equal("body.status", "NORMAL")
            .assert_equal("body.role", "CUSTOMER_MASTER")
            .assert_equal("body.userTel", "13787340624")
        ),
    ]


if __name__ == "__main__":
    TestCaseUserInfo().test_start()
