# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Buildings/create_UnAvailable_rooms.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Buildings.buildings_test import TestCaseBuildings as Buildings


class TestCaseCreateUnavailableRooms(HttpRunner):

    config = (
        Config("空间管理--房源列表--新增不可招商房源")
        .variables(
            **{
                "access_token": "${get_token()}",
                "room_number": "${random_int(1,199)}",
                "areaSize": "${str_to_int(10)}",
                "beginDate": "2021-01-01",
                "endDate": "2021-12-31",
            }
        )
        .export(
            *["building_id", "total_numberOfManagement", "available_size", "total_size"]
        )
    )

    teststeps = [
        Step(RunTestCase("获取楼宇id").call(Buildings).export(*["building_id"])),
        Step(
            RunRequest("楼宇统计---获取管理面积")
            .get("${ENV(api_url)}/data-statistics/building/summary")
            .with_params(
                **{
                    "ids": "$building_id",
                    "portfolioType": "BUILDING",
                    "statisticSpaceType": "ROOM",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .extract()
            .with_jmespath("body.numberOfManagement", "total_numberOfManagement")
            .with_jmespath("body.numberOfAvailable", "available_size")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("新增不可招商房源")
            .post("${ENV(api_url)}/buildings/$building_id/rooms")
            .with_headers(
                **{
                    "accept": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "areaSize": "$areaSize",
                    "buildingId": "$building_id",
                    "cubicleUpdateRequests": [],
                    "floorName": "1",
                    "jsonData": '[{"required":false,"fieldName":"建筑面积","fieldType":"NUMBER","systemField":true},{"required":false,"fieldName":"装修","fieldType":"SINGLE_SELECT","values":["不限","毛坯","简装","精装"],"systemField":true},{"required":false,"fieldName":"预租单价","fieldType":"NUMBER","systemField":true}]',
                    "marketingAvailable": "false",
                    "realAreaSize": "$areaSize",
                    "roomNumber": "$room_number",
                    "spaceType": "ROOM",
                }
            )
            .teardown_hook("${wait($response,1)}")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("新增不可招商房源后，检查房源列表管理面积是否正确")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .extract()
            .with_jmespath("body.numberOfManagement", "total_size")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal(
                "body.numberOfManagement",
                "${sum_float($total_numberOfManagement, $areaSize)}",
            )
        ),
        Step(
            RunRequest("新增不可招商房源后，检查房源列表可招商面积是否正确")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM",
                    "available": True,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.numberOfManagement", "$available_size")
        ),
        Step(
            RunRequest("检查新增不可招商房源后，楼宇统计--管理面积、可招商面积是否正确")
            .get("${ENV(api_url)}/data-statistics/building/summary")
            .with_params(
                **{
                    "ids": "$building_id",
                    "portfolioType": "BUILDING",
                    "statisticSpaceType": "ROOM",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.numberOfManagement", "$total_size")
            .assert_equal("body.numberOfAvailable", "$available_size")
        ),
    ]


if __name__ == "__main__":
    TestCaseCreateUnavailableRooms().test_start()
