# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Buildings/rooms/room_statistics.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Buildings.buildings_test import TestCaseBuildings as Buildings


class TestCaseRoomStatistics(HttpRunner):

    config = (
        Config("空间管理--房源列表数据概览")
        .variables(
            **{
                "access_token": "${get_token()}",
                "beginDate": "2021-01-01",
                "endDate": "2021-12-31",
            }
        )
        .export(*["building_id"])
    )

    teststeps = [
        Step(RunTestCase("获取楼宇id").call(Buildings).export(*["building_id"])),
        Step(
            RunRequest("获取房态列表数据概览")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": True,
                    "loadRentingInfo": False,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM,CUBICLE",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.numberOfManagement", "${total_roomSize()}")
            .assert_equal("body.roomCount", "${total_roomCount()}")
        ),
        Step(
            RunRequest("房态列表数据概览-按房号查询")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": True,
                    "loadRentingInfo": False,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM,CUBICLE",
                    "keyword": 101,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取房源列表-房源数据概览")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("房源列表数据概览-按房号查询")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM",
                    "keyword": 101,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取房源列表-工位房源数据概览")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "CUBICLE",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("工位房源数据概览-按房号查询")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "CUBICLE",
                    "keyword": 101,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取房源列表-房源、工位房源数据概览")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM,CUBICLE",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("房源、工位房源数据概览-按房号查询")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM,CUBICLE",
                    "keyword": 101,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取房源列表-可招商房源数据概览")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM",
                    "available": True,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("可招商房源数据概览-按房号查询")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM",
                    "available": True,
                    "keyword": 101,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取房源列表-可招商工位房源数据概览")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "CUBICLE",
                    "available": True,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("可招商工位房源数据概览-按房号查询")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "CUBICLE",
                    "available": True,
                    "keyword": 101,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取房源列表-可招商房源、工位房源数据概览")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM,CUBICLE",
                    "available": True,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("可招商房源、工位房源数据概览-按房号查询")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM,CUBICLE",
                    "available": True,
                    "keyword": 101,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取房源列表-不可招商房源数据概览")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM",
                    "available": False,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("房源列表-不可招商房源数据概览-按房号查询")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM",
                    "available": False,
                    "keyword": 101,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取房源列表-不可招商工位房源数据概览")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "CUBICLE",
                    "available": False,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("房源列表-不可招商工位房源数据概览-按房号查询")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "CUBICLE",
                    "available": False,
                    "keyword": 101,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取房源列表-不可招商房源、工位房源数据概览")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM,CUBICLE",
                    "available": False,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("房源列表-不可招商房源、工位房源数据概览-按房号查询")
            .get("${ENV(api_url)}/buildings/room/statistics")
            .with_params(
                **{
                    "beginDate": "$beginDate",
                    "endDate": "$endDate",
                    "buildingIds": "$building_id",
                    "loadOccupancyInfo": False,
                    "loadRentingInfo": True,
                    "spaceType": "ROOM",
                    "spaceTypes": "ROOM,CUBICLE",
                    "available": False,
                    "keyword": 101,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseRoomStatistics().test_start()
