# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Resource/cubicles.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Buildings.buildings_test import TestCaseBuildings as Buildings


class TestCaseCubicles(HttpRunner):

    config = (
        Config("空间管理--工位列表")
        .variables(**{"access_token": "${get_token()}"})
        .export(*["building_id"])
    )

    teststeps = [
        Step(RunTestCase("获取楼宇id").call(Buildings).export(*["building_id"])),
        Step(
            RunRequest("获取工位列表")
            .get("${ENV(api_url)}/buildings/cubicles")
            .with_params(**{"buildingIds": "$building_id", "size": "100"})
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.size", 100)
        ),
    ]


if __name__ == "__main__":
    TestCaseCubicles().test_start()
