# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Buildings/cubicle/delete_cubicle.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Buildings.buildings_test import TestCaseBuildings as Buildings


class TestCaseDeleteCubicle(HttpRunner):

    config = (
        Config("删除工位")
        .variables(
            **{
                "access_token": "${get_token()}",
                "room_number": "${random_int(201,299)}",
                "areaSize": "${str_to_int(20)}",
            }
        )
        .verify(False)
        .export(*["building_id", "cubicle_id", "room_id", "cubicleId"])
    )

    teststeps = [
        Step(RunTestCase("获取楼宇id").call(Buildings).export(*["building_id"])),
        Step(
            RunRequest("新增可招商工位类型房源")
            .post("${ENV(api_url)}/buildings/$building_id/rooms")
            .with_headers(**{"authorization": "Bearer $access_token"})
            .with_json(
                {
                    "areaSize": "$areaSize",
                    "buildingId": "$building_id",
                    "cubicleUpdateRequests": [
                        {"marketingAvailable": "true", "number": "1"}
                    ],
                    "floorName": "2",
                    "jsonData": '[{"required":false,"fieldName":"建筑面积","fieldType":"NUMBER","systemField":true},{"required":false,"fieldName":"装修","fieldType":"SINGLE_SELECT","values":["不限","毛坯","简装","精装"],"systemField":true},{"required":false,"fieldName":"预租单价","fieldType":"NUMBER","systemField":true}]',
                    "marketingAvailable": "true",
                    "realAreaSize": "$areaSize",
                    "roomNumber": "$room_number",
                    "spaceType": "CUBICLE",
                }
            )
            .extract()
            .with_jmespath("body", "room_id")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("创建工位")
            .post("${ENV(api_url)}/buildings/rooms/$room_id/cubicles")
            .with_headers(
                **{
                    "accept": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "customFieldJsonData": [],
                    "jsonData": "[]",
                    "marketingAvailable": True,
                    "number": "2",
                }
            )
            .teardown_hook("${wait($response, 1)}")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取工位id")
            .get("${ENV(api_url)}/buildings/cubicles")
            .with_params(**{"buildingIds": "$building_id", "size": "100"})
            .with_headers(**{"authorization": "Bearer $access_token"})
            .extract()
            .with_jmespath("body.content[0].id", "cubicle_id")
            .with_jmespath("body.length(content)", "cubicle_count")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("工位列表-删除工位")
            .delete("${ENV(api_url)}/buildings/cubicles/$cubicle_id")
            .with_headers(
                **{
                    "accept": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("删除工位后，检查工位数")
            .get("${ENV(api_url)}/buildings/cubicles")
            .with_params(**{"buildingIds": "$building_id", "size": "100"})
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.length(content)", "${reduce_two($cubicle_count, 1)}")
        ),
        Step(
            RunRequest("获取工位类型房源中的工位")
            .get("${ENV(api_url)}/buildings/room/$room_id/cubicles")
            .with_headers(**{"authorization": "Bearer $access_token"})
            .extract()
            .with_jmespath("body[0].id", "cubicleId")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("房源列表-删除工位")
            .delete("${ENV(api_url)}/buildings/cubicles/$cubicleId")
            .with_headers(
                **{
                    "accept": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseDeleteCubicle().test_start()
