# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Statistics/assets/cashflows.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Account.create_bills_test import TestCaseCreateBills as CreateBills


class TestCaseCashflows(HttpRunner):

    config = (
        Config("数据舱-资产评估-现金流")
        .variables(
            **{
                "access_token": "${get_token()}",
                "endDate": "2021-12-31",
                "startDate": "2021-01-01",
            }
        )
        .export(*["building_id"])
    )

    teststeps = [
        Step(
            RunTestCase("添加账单收入、支出数据")
            .call(CreateBills)
            .export(*["room_id", "building_id"])
        ),
        Step(
            RunRequest("资产评估--现金流--按租金+收支流水、月统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "MONTH",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[8].costAmount", 100)
            .assert_equal("body[8].incomeAmount", 100)
            .assert_equal("body[8].worthAmount", 0)
        ),
        Step(
            RunRequest("资产评估--现金流--按租金+租金保证金+收支流水、月统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "MONTH",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[7].costAmount", 0)
            .assert_equal("body[7].incomeAmount", 3041.67)
            .assert_equal("body[7].worthAmount", 3041.67)
            .assert_equal("body[8].costAmount", 120)
            .assert_equal("body[8].incomeAmount", 150)
            .assert_equal("body[8].worthAmount", 30)
        ),
        Step(
            RunRequest("资产评估--现金流--收支流水、按月统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "MONTH",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[7].costAmount", 0)
            .assert_equal("body[7].incomeAmount", 3041.67)
            .assert_equal("body[7].worthAmount", 3041.67)
            .assert_equal("body[8].costAmount", 155.5)
            .assert_equal("body[8].incomeAmount", 165.5)
            .assert_equal("body[8].worthAmount", 10)
        ),
        Step(
            RunRequest("资产评估--现金流--按租金+收支流水、季度统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "QUARTER",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[2].costAmount", 100)
            .assert_equal("body[2].incomeAmount", 100)
            .assert_equal("body[2].worthAmount", 0)
        ),
        Step(
            RunRequest("资产评估--现金流--按租金+租金保证金+收支流水、季度统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "QUARTER",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[2].costAmount", 120)
            .assert_equal("body[2].incomeAmount", 3191.67)
            .assert_equal("body[2].worthAmount", 3071.67)
        ),
        Step(
            RunRequest("资产评估--现金流--收支流水、按季度统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "QUARTER",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[2].costAmount", 155.5)
            .assert_equal("body[2].incomeAmount", 3207.17)
            .assert_equal("body[2].worthAmount", 3051.67)
        ),
        Step(
            RunRequest("资产评估--现金流--按租金+收支流水、年统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "YEAR",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[0].costAmount", 100)
            .assert_equal("body[0].incomeAmount", 100)
            .assert_equal("body[0].worthAmount", 0)
        ),
        Step(
            RunRequest("资产评估--现金流--按租金+租金保证金+收支流水、年统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "YEAR",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[0].costAmount", 120)
            .assert_equal("body[0].incomeAmount", 3191.67)
            .assert_equal("body[0].worthAmount", 3071.67)
        ),
        Step(
            RunRequest("资产评估--现金流--收支流水、按年统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "YEAR",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[0].costAmount", 155.5)
            .assert_equal("body[0].incomeAmount", 3207.17)
            .assert_equal("body[0].worthAmount", 3051.67)
        ),
        Step(
            RunRequest("资产评估--现金流--按租金+结转、月统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "MONTH",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[8].costAmount", 0)
            .assert_equal("body[8].incomeAmount", 98.12)
            .assert_equal("body[8].worthAmount", 98.12)
        ),
        Step(
            RunRequest("资产评估--现金流--按租金+租金保证金+结转、月统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "MONTH",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[8].costAmount", 98.12)
            .assert_equal("body[8].incomeAmount", 98.12)
            .assert_equal("body[8].worthAmount", 0)
        ),
        Step(
            RunRequest("资产评估--现金流--结转、月统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "MONTH",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[8].costAmount", 98.12)
            .assert_equal("body[8].incomeAmount", 98.12)
            .assert_equal("body[8].worthAmount", 0)
        ),
        Step(
            RunRequest("资产评估--现金流--租金+结转、按季统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "QUARTER",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[2].costAmount", 0)
            .assert_equal("body[2].incomeAmount", 98.12)
            .assert_equal("body[2].worthAmount", 98.12)
        ),
        Step(
            RunRequest("资产评估--现金流--租金+租金保证金+结转、按季统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "QUARTER",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[2].costAmount", 98.12)
            .assert_equal("body[2].incomeAmount", 98.12)
            .assert_equal("body[2].worthAmount", 0)
        ),
        Step(
            RunRequest("资产评估--现金流--结转、按季统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "QUARTER",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[2].costAmount", 98.12)
            .assert_equal("body[2].incomeAmount", 98.12)
            .assert_equal("body[2].worthAmount", 0)
        ),
        Step(
            RunRequest("资产评估--现金流--租金+结转、按年统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "YEAR",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[0].costAmount", 0)
            .assert_equal("body[0].incomeAmount", 98.12)
            .assert_equal("body[0].worthAmount", 98.12)
        ),
        Step(
            RunRequest("资产评估--现金流--租金+租金保证金+结转、按年统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "YEAR",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[0].costAmount", 98.12)
            .assert_equal("body[0].incomeAmount", 98.12)
            .assert_equal("body[0].worthAmount", 0)
        ),
        Step(
            RunRequest("资产评估--现金流--结转、按年统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "YEAR",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[0].costAmount", 98.12)
            .assert_equal("body[0].incomeAmount", 98.12)
            .assert_equal("body[0].worthAmount", 0)
        ),
        Step(
            RunRequest("资产评估--现金流--按租金+收支流水+结转、月统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD,CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "MONTH",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[8].costAmount", 100)
            .assert_equal("body[8].incomeAmount", 198.12)
            .assert_equal("body[8].worthAmount", 98.12)
        ),
        Step(
            RunRequest("资产评估--现金流--按租金+租金保证金+收支流水+结转、月统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD,CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "MONTH",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[7].costAmount", 0)
            .assert_equal("body[7].incomeAmount", 3041.67)
            .assert_equal("body[7].worthAmount", 3041.67)
            .assert_equal("body[8].costAmount", 218.12)
            .assert_equal("body[8].incomeAmount", 248.12)
            .assert_equal("body[8].worthAmount", 30)
        ),
        Step(
            RunRequest("资产评估--现金流--收支流水+结转、月统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD,CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "MONTH",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[7].costAmount", 0)
            .assert_equal("body[7].incomeAmount", 3041.67)
            .assert_equal("body[7].worthAmount", 3041.67)
            .assert_equal("body[8].costAmount", 253.62)
            .assert_equal("body[8].incomeAmount", 263.62)
            .assert_equal("body[8].worthAmount", 10)
        ),
        Step(
            RunRequest("资产评估--现金流--按租金+收支流水+结转、季统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD,CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "QUARTER",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[2].costAmount", 100)
            .assert_equal("body[2].incomeAmount", 198.12)
            .assert_equal("body[2].worthAmount", 98.12)
        ),
        Step(
            RunRequest("资产评估--现金流--按租金+租金保证金+收支流水+结转、季统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD,CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "QUARTER",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[2].costAmount", 218.12)
            .assert_equal("body[2].incomeAmount", 3289.79)
            .assert_equal("body[2].worthAmount", 3071.67)
        ),
        Step(
            RunRequest("资产评估--现金流--收支流水+结转、季统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD,CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "QUARTER",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[2].costAmount", 253.62)
            .assert_equal("body[2].incomeAmount", 3305.29)
            .assert_equal("body[2].worthAmount", 3051.67)
        ),
        Step(
            RunRequest("资产评估--现金流--按租金+收支流水+结转、年统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD,CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "YEAR",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[0].costAmount", 100)
            .assert_equal("body[0].incomeAmount", 198.12)
            .assert_equal("body[0].worthAmount", 98.12)
        ),
        Step(
            RunRequest("资产评估--现金流--按租金+租金保证金+收支流水+结转、年统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD,CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "YEAR",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[0].costAmount", 218.12)
            .assert_equal("body[0].incomeAmount", 3289.79)
            .assert_equal("body[0].worthAmount", 3071.67)
        ),
        Step(
            RunRequest("资产评估--现金流--收支流水+结转、年统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD,CASH_MATCH",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "temporalUnit": "YEAR",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[0].costAmount", 253.62)
            .assert_equal("body[0].incomeAmount", 3305.29)
            .assert_equal("body[0].worthAmount", 3051.67)
        ),
        Step(
            RunRequest("数据舱--现金流详情--租金+收支流水、按月查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "2021-09-30",
                    "startDate": "2021-09-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "MONTH",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].billType", "租金")
            .assert_equal("body.content[0].amount", 100)
            .assert_equal("body.content[1].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[1].action", "OUT")
            .assert_equal("body.content[1].billType", "租金")
            .assert_equal("body.content[1].amount", 100)
        ),
        Step(
            RunRequest("数据舱--现金流详情--租金+租金保证金+收支流水、按月查看-8")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "2021-08-31",
                    "startDate": "2021-08-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "MONTH",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].billType", "租金保证金")
            .assert_equal("body.content[0].amount", 3041.67)
        ),
        Step(
            RunRequest("数据舱--现金流详情--租金+租金保证金+收支流水、按月查看-9")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "2021-09-30",
                    "startDate": "2021-09-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "MONTH",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].billType", "租金")
            .assert_equal("body.content[0].amount", 100)
            .assert_equal("body.content[1].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].billType", "租金保证金")
            .assert_equal("body.content[1].amount", 50)
            .assert_equal("body.content[2].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[2].action", "OUT")
            .assert_equal("body.content[2].billType", "租金")
            .assert_equal("body.content[2].amount", 100)
            .assert_equal("body.content[3].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[3].action", "OUT")
            .assert_equal("body.content[3].billType", "租金保证金")
            .assert_equal("body.content[3].amount", 20)
        ),
        Step(
            RunRequest("数据舱--现金流详情--收支流水、按月查看-8")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "2021-08-31",
                    "startDate": "2021-08-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "MONTH",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].billType", "租金保证金")
            .assert_equal("body.content[0].amount", 3041.67)
        ),
        Step(
            RunRequest("数据舱--现金流详情--收支流水、按月查看-9")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "2021-09-30",
                    "startDate": "2021-09-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "MONTH",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].billType", "租金")
            .assert_equal("body.content[0].amount", 100)
            .assert_equal("body.content[1].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].billType", "租金保证金")
            .assert_equal("body.content[1].amount", 50)
            .assert_equal("body.content[2].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[2].action", "IN")
            .assert_equal("body.content[2].billType", "物业费")
            .assert_equal("body.content[2].amount", 15.5)
            .assert_equal("body.content[3].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[3].action", "OUT")
            .assert_equal("body.content[3].billType", "租金")
            .assert_equal("body.content[3].amount", 100)
            .assert_equal("body.content[4].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[4].action", "OUT")
            .assert_equal("body.content[4].billType", "租金保证金")
            .assert_equal("body.content[4].amount", 20)
            .assert_equal("body.content[5].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[5].action", "OUT")
            .assert_equal("body.content[5].billType", "物业费")
            .assert_equal("body.content[5].amount", 35.5)
        ),
        Step(
            RunRequest("数据舱--现金流详情--租金+收支流水、按季度查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "2021-09-30",
                    "startDate": "2021-07-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "QUARTER",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].billType", "租金")
            .assert_equal("body.content[0].amount", 100)
            .assert_equal("body.content[1].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[1].action", "OUT")
            .assert_equal("body.content[1].billType", "租金")
            .assert_equal("body.content[1].amount", 100)
        ),
        Step(
            RunRequest("数据舱--现金流详情--租金+租金保证金+收支流水、按季度查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "2021-09-30",
                    "startDate": "2021-07-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "QUARTER",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].billType", "租金保证金")
            .assert_equal("body.content[0].amount", 3041.67)
            .assert_equal("body.content[1].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].billType", "租金")
            .assert_equal("body.content[1].amount", 100)
            .assert_equal("body.content[2].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[2].action", "IN")
            .assert_equal("body.content[2].billType", "租金保证金")
            .assert_equal("body.content[2].amount", 50)
            .assert_equal("body.content[3].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[3].action", "OUT")
            .assert_equal("body.content[3].billType", "租金")
            .assert_equal("body.content[3].amount", 100)
            .assert_equal("body.content[4].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[4].action", "OUT")
            .assert_equal("body.content[4].billType", "租金保证金")
            .assert_equal("body.content[4].amount", 20)
        ),
        Step(
            RunRequest("数据舱--现金流详情--收支流水、按季度查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "2021-09-30",
                    "startDate": "2021-07-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "QUARTER",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].billType", "租金保证金")
            .assert_equal("body.content[0].amount", 3041.67)
            .assert_equal("body.content[1].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].billType", "租金")
            .assert_equal("body.content[1].amount", 100)
            .assert_equal("body.content[2].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[2].action", "IN")
            .assert_equal("body.content[2].billType", "租金保证金")
            .assert_equal("body.content[2].amount", 50)
            .assert_equal("body.content[3].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[3].action", "IN")
            .assert_equal("body.content[3].billType", "物业费")
            .assert_equal("body.content[3].amount", 15.5)
            .assert_equal("body.content[4].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[4].action", "OUT")
            .assert_equal("body.content[4].billType", "租金")
            .assert_equal("body.content[4].amount", 100)
            .assert_equal("body.content[5].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[5].action", "OUT")
            .assert_equal("body.content[5].billType", "租金保证金")
            .assert_equal("body.content[5].amount", 20)
            .assert_equal("body.content[6].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[6].action", "OUT")
            .assert_equal("body.content[6].billType", "物业费")
            .assert_equal("body.content[6].amount", 35.5)
        ),
        Step(
            RunRequest("数据舱--现金流详情--租金+收支流水、按年查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "startDate": "2021-01-01",
                    "endDate": "2021-12-31",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "YEAR",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].billType", "租金")
            .assert_equal("body.content[0].amount", 100)
            .assert_equal("body.content[1].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[1].action", "OUT")
            .assert_equal("body.content[1].billType", "租金")
            .assert_equal("body.content[1].amount", 100)
        ),
        Step(
            RunRequest("数据舱--现金流详情--租金+租金保证金+收支流水、按年查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "startDate": "2021-01-01",
                    "endDate": "2021-12-31",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "YEAR",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].billType", "租金保证金")
            .assert_equal("body.content[0].amount", 3041.67)
            .assert_equal("body.content[1].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].billType", "租金")
            .assert_equal("body.content[1].amount", 100)
            .assert_equal("body.content[2].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[2].action", "IN")
            .assert_equal("body.content[2].billType", "租金保证金")
            .assert_equal("body.content[2].amount", 50)
            .assert_equal("body.content[3].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[3].action", "OUT")
            .assert_equal("body.content[3].billType", "租金")
            .assert_equal("body.content[3].amount", 100)
            .assert_equal("body.content[4].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[4].action", "OUT")
            .assert_equal("body.content[4].billType", "租金保证金")
            .assert_equal("body.content[4].amount", 20)
        ),
        Step(
            RunRequest("数据舱--现金流详情--收支流水、按年查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "startDate": "2021-01-01",
                    "endDate": "2021-12-31",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "YEAR",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].billType", "租金保证金")
            .assert_equal("body.content[0].amount", 3041.67)
            .assert_equal("body.content[1].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].billType", "租金")
            .assert_equal("body.content[1].amount", 100)
            .assert_equal("body.content[2].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[2].action", "IN")
            .assert_equal("body.content[2].billType", "租金保证金")
            .assert_equal("body.content[2].amount", 50)
            .assert_equal("body.content[3].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[3].action", "IN")
            .assert_equal("body.content[3].billType", "物业费")
            .assert_equal("body.content[3].amount", 15.5)
            .assert_equal("body.content[4].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[4].action", "OUT")
            .assert_equal("body.content[4].billType", "租金")
            .assert_equal("body.content[4].amount", 100)
            .assert_equal("body.content[5].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[5].action", "OUT")
            .assert_equal("body.content[5].billType", "租金保证金")
            .assert_equal("body.content[5].amount", 20)
            .assert_equal("body.content[6].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[6].action", "OUT")
            .assert_equal("body.content[6].billType", "物业费")
            .assert_equal("body.content[6].amount", 35.5)
        ),
        Step(
            RunRequest("数据舱--现金流详情--租金+结转、按月查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "2021-09-30",
                    "startDate": "2021-09-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "MONTH",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].billType", "租金")
            .assert_equal("body.content[0].amount", 98.12)
        ),
        Step(
            RunRequest("数据舱--现金流详情--租金+租金保证金+结转、按月查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "2021-09-30",
                    "startDate": "2021-09-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "MONTH",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "OUT")
            .assert_equal("body.content[0].billType", "租金保证金")
            .assert_equal("body.content[0].amount", 98.12)
            .assert_equal("body.content[1].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].billType", "租金")
            .assert_equal("body.content[1].amount", 98.12)
        ),
        Step(
            RunRequest("数据舱--现金流详情--结转、按月查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "2021-09-30",
                    "startDate": "2021-09-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "MONTH",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "OUT")
            .assert_equal("body.content[0].billType", "租金保证金")
            .assert_equal("body.content[0].amount", 98.12)
            .assert_equal("body.content[1].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].billType", "租金")
            .assert_equal("body.content[1].amount", 98.12)
        ),
        Step(
            RunRequest("数据舱--现金流详情--租金+结转、按季查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "2021-09-30",
                    "startDate": "2021-07-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "QUARTER",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].billType", "租金")
            .assert_equal("body.content[0].amount", 98.12)
        ),
        Step(
            RunRequest("数据舱--现金流详情--租金+租金保证金+结转、按季查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "2021-09-30",
                    "startDate": "2021-07-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "QUARTER",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "OUT")
            .assert_equal("body.content[0].billType", "租金保证金")
            .assert_equal("body.content[0].amount", 98.12)
            .assert_equal("body.content[1].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].billType", "租金")
            .assert_equal("body.content[1].amount", 98.12)
        ),
        Step(
            RunRequest("数据舱--现金流详情--结转、按季查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "2021-09-30",
                    "startDate": "2021-07-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "QUARTER",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "OUT")
            .assert_equal("body.content[0].billType", "租金保证金")
            .assert_equal("body.content[0].amount", 98.12)
            .assert_equal("body.content[1].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].billType", "租金")
            .assert_equal("body.content[1].amount", 98.12)
        ),
        Step(
            RunRequest("数据舱--现金流详情--租金+结转、按年查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "2021-12-31",
                    "startDate": "2021-01-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "YEAR",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].billType", "租金")
            .assert_equal("body.content[0].amount", 98.12)
        ),
        Step(
            RunRequest("数据舱--现金流详情--租金+租金保证金+结转、按年查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "2021-12-31",
                    "startDate": "2021-01-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "YEAR",
                    "billTypes": "租金,租金保证金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "OUT")
            .assert_equal("body.content[0].billType", "租金保证金")
            .assert_equal("body.content[0].amount", 98.12)
            .assert_equal("body.content[1].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].billType", "租金")
            .assert_equal("body.content[1].amount", 98.12)
        ),
        Step(
            RunRequest("数据舱--现金流详情--结转、按年查看")
            .get("${ENV(api_url)}/assets/cashflows/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CARRY_FORWARD",
                    "endDate": "2021-12-31",
                    "startDate": "2021-01-01",
                    "page": "0",
                    "size": "20",
                    "temporalUnit": "YEAR",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[0].action", "OUT")
            .assert_equal("body.content[0].billType", "租金保证金")
            .assert_equal("body.content[0].amount", 98.12)
            .assert_equal("body.content[1].tenantName", "湖南神雀网络科技有限公司")
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].billType", "租金")
            .assert_equal("body.content[1].amount", 98.12)
        ),
        Step(
            RunRequest("删除楼宇")
            .delete("${ENV(api_url)}/buildings/$building_id")
            .with_headers(
                **{
                    "authorization": "Bearer $access_token",
                    "content-type": "application/json; charset=utf-8",
                }
            )
            .validate()
            .assert_equal("status_code", 204)
        ),
    ]


if __name__ == "__main__":
    TestCaseCashflows().test_start()
