# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Statistics/assets/cashflows.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Buildings.buildings_test import TestCaseBuildings as Buildings


class TestCaseCashflows(HttpRunner):

    config = (
        Config("数据舱--现金流")
        .variables(
            **{
                "access_token": "${get_token()}",
                "month_endDate": "2021-12-31",
                "month_startDate": "2021-01-01",
            }
        )
        .export(*["building_id"])
    )

    teststeps = [
        Step(RunTestCase("获取楼宇id").call(Buildings).export(*["building_id"])),
        Step(
            RunRequest("数据舱--现金流--按月统计")
            .get("${ENV(api_url)}/assets/cashflows")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "domainTypes": "CASH_MATCH",
                    "endDate": "$month_endDate",
                    "startDate": "$month_startDate",
                    "temporalUnit": "MONTH",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseCashflows().test_start()
