# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Statistics/assets/collection_rates.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Account.create_bills_test import TestCaseCreateBills as CreateBills


class TestCaseCollectionRates(HttpRunner):

    config = (
        Config("数据舱--收缴率")
        .variables(
            **{
                "access_token": "${get_token()}",
                "endDate": "2021-12-31",
                "startDate": "2021-01-01",
            }
        )
        .verify(False)
        .export(*["building_id"])
    )

    teststeps = [
        Step(
            RunTestCase("添加账单收入、支出数据")
            .call(CreateBills)
            .export(*["building_id", "room_id"])
        ),
        Step(
            RunRequest("收缴率--租金、按月查询")
            .get("${ENV(api_url)}/assets/collection-rates")
            .with_params(
                **{
                    "billSelectAmount": "AMOUNT",
                    "buildingIds": "$building_id",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "switchValue": "percentage",
                    "temporalUnit": "MONTH",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[7].cashFlowAmount", 98.12)
            .assert_equal("body[7].amount", 98.12)
            .assert_equal("body[7].currentCashFlowAmount", 98.12)
            .assert_equal("body[8].cashFlowAmount", 100)
            .assert_equal("body[8].amount", 3241.67)
            .assert_equal("body[8].currentCashFlowAmount", 100)
            .assert_equal("body[7].totalCollectionRate", 1)
            .assert_equal("body[7].currentCollectionRate", 1)
            .assert_equal("body[8].totalCollectionRate", 0.0308)
            .assert_equal("body[8].currentCollectionRate", 0.0308)
        ),
        Step(
            RunRequest("收缴率--租金+物业费、按月查询")
            .get("${ENV(api_url)}/assets/collection-rates")
            .with_params(
                **{
                    "billSelectAmount": "AMOUNT",
                    "buildingIds": "$building_id",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "switchValue": "percentage",
                    "temporalUnit": "MONTH",
                    "billTypes": "租金,物业费",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[7].cashFlowAmount", 98.12)
            .assert_equal("body[7].amount", 98.12)
            .assert_equal("body[7].currentCashFlowAmount", 98.12)
            .assert_equal("body[8].cashFlowAmount", 115.5)
            .assert_equal("body[8].amount", 3257.17)
            .assert_equal("body[8].currentCashFlowAmount", 115.5)
            .assert_equal("body[7].totalCollectionRate", 1)
            .assert_equal("body[7].currentCollectionRate", 1)
            .assert_equal("body[8].totalCollectionRate", 0.0355)
            .assert_equal("body[8].currentCollectionRate", 0.0355)
        ),
        Step(
            RunRequest("收缴率--按月查询")
            .get("${ENV(api_url)}/assets/collection-rates")
            .with_params(
                **{
                    "billSelectAmount": "AMOUNT",
                    "buildingIds": "$building_id",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "switchValue": "percentage",
                    "temporalUnit": "MONTH",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[8].cashFlowAmount", 165.5)
            .assert_equal("body[8].amount", 6348.84)
            .assert_equal("body[8].currentCashFlowAmount", 165.5)
            .assert_equal("body[7].totalCollectionRate", 1)
            .assert_equal("body[7].currentCollectionRate", 1)
            .assert_equal("body[8].totalCollectionRate", 0.0261)
            .assert_equal("body[8].currentCollectionRate", 0.0261)
        ),
        Step(
            RunRequest("收缴率--租金、按季查询")
            .get("${ENV(api_url)}/assets/collection-rates")
            .with_params(
                **{
                    "billSelectAmount": "AMOUNT",
                    "buildingIds": "$building_id",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "switchValue": "percentage",
                    "temporalUnit": "QUARTER",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[2].cashFlowAmount", 198.12)
            .assert_equal("body[2].amount", 3339.79)
            .assert_equal("body[2].currentCashFlowAmount", 198.12)
            .assert_equal("body[2].totalCollectionRate", 0.0593)
            .assert_equal("body[2].currentCollectionRate", 0.0593)
        ),
        Step(
            RunRequest("收缴率--租金+物业费、按季查询")
            .get("${ENV(api_url)}/assets/collection-rates")
            .with_params(
                **{
                    "billSelectAmount": "AMOUNT",
                    "buildingIds": "$building_id",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "switchValue": "percentage",
                    "temporalUnit": "QUARTER",
                    "billTypes": "租金,物业费",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[2].cashFlowAmount", 213.62)
            .assert_equal("body[2].amount", 3355.29)
            .assert_equal("body[2].currentCashFlowAmount", 213.62)
            .assert_equal("body[2].totalCollectionRate", 0.0637)
            .assert_equal("body[2].currentCollectionRate", 0.0637)
        ),
        Step(
            RunRequest("收缴率--按季查询")
            .get("${ENV(api_url)}/assets/collection-rates")
            .with_params(
                **{
                    "billSelectAmount": "AMOUNT",
                    "buildingIds": "$building_id",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "switchValue": "percentage",
                    "temporalUnit": "QUARTER",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[2].cashFlowAmount", 263.62)
            .assert_equal("body[2].amount", 6446.96)
            .assert_equal("body[2].currentCashFlowAmount", 263.62)
            .assert_equal("body[2].totalCollectionRate", 0.0409)
            .assert_equal("body[2].currentCollectionRate", 0.0409)
        ),
        Step(
            RunRequest("收缴率--租金、按年查询")
            .get("${ENV(api_url)}/assets/collection-rates")
            .with_params(
                **{
                    "billSelectAmount": "AMOUNT",
                    "buildingIds": "$building_id",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "switchValue": "percentage",
                    "temporalUnit": "YEAR",
                    "billTypes": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[0].cashFlowAmount", 198.12)
            .assert_equal("body[0].amount", 3339.79)
            .assert_equal("body[0].currentCashFlowAmount", 198.12)
            .assert_equal("body[0].totalCollectionRate", 0.0593)
            .assert_equal("body[0].currentCollectionRate", 0.0593)
        ),
        Step(
            RunRequest("收缴率--租金+物业费、按年查询")
            .get("${ENV(api_url)}/assets/collection-rates")
            .with_params(
                **{
                    "billSelectAmount": "AMOUNT",
                    "buildingIds": "$building_id",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "switchValue": "percentage",
                    "temporalUnit": "YEAR",
                    "billTypes": "租金,租物业费",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[0].cashFlowAmount", 213.62)
            .assert_equal("body[0].amount", 3355.29)
            .assert_equal("body[0].currentCashFlowAmount", 213.62)
            .assert_equal("body[0].totalCollectionRate", 0.0637)
            .assert_equal("body[0].currentCollectionRate", 0.0637)
        ),
        Step(
            RunRequest("收缴率--按年查询")
            .get("${ENV(api_url)}/assets/collection-rates")
            .with_params(
                **{
                    "billSelectAmount": "AMOUNT",
                    "buildingIds": "$building_id",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "switchValue": "percentage",
                    "temporalUnit": "YEAR",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[0].cashFlowAmount", 263.62)
            .assert_equal("body[0].amount", 6446.96)
            .assert_equal("body[0].currentCashFlowAmount", 263.62)
            .assert_equal("body[0].totalCollectionRate", 0.0409)
            .assert_equal("body[0].currentCollectionRate", 0.0409)
        ),
        Step(
            RunRequest("收缴率详情--租金、按月查询-8")
            .get("${ENV(api_url)}/v2/bills/list")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "page": "0",
                    "payDateFrom": "2021-08-01",
                    "payDateTo": "2021-08-31",
                    "size": "100",
                    "type": "租金",
                    "isDeposit": False,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].typeName", "租金")
            .assert_equal("body.content[0].theoryAmount", 98.12)
            .assert_equal("body.content[0].payedAmount", 0)
            .assert_equal("body.content[0].primeAmount", 3041.67)
        ),
        Step(
            RunRequest("收缴率详情--租金、按月查询-9")
            .get("${ENV(api_url)}/v2/bills/list")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "page": "0",
                    "payDateFrom": "2021-09-01",
                    "payDateTo": "2021-09-30",
                    "size": "100",
                    "type": "租金",
                    "isDeposit": False,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].typeName", "租金")
            .assert_equal("body.content[0].theoryAmount", 200)
            .assert_equal("body.content[0].payedAmount", 100)
            .assert_equal("body.content[0].primeAmount", 200)
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].typeName", "租金")
            .assert_equal("body.content[1].theoryAmount", 3041.67)
            .assert_equal("body.content[1].payedAmount", 0)
            .assert_equal("body.content[1].primeAmount", 3041.67)
        ),
        Step(
            RunRequest("收缴率详情--租金+物业费、按月查询-8")
            .get("${ENV(api_url)}/v2/bills/list")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "page": "0",
                    "payDateFrom": "2021-08-01",
                    "payDateTo": "2021-08-31",
                    "size": "100",
                    "type": "租金,物业费",
                    "isDeposit": False,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].typeName", "租金")
            .assert_equal("body.content[0].theoryAmount", 98.12)
            .assert_equal("body.content[0].payedAmount", 0)
            .assert_equal("body.content[0].primeAmount", 3041.67)
        ),
        Step(
            RunRequest("收缴率详情--租金+物业费、按月查询-9")
            .get("${ENV(api_url)}/v2/bills/list")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "page": "0",
                    "payDateFrom": "2021-09-01",
                    "payDateTo": "2021-09-30",
                    "size": "100",
                    "type": "租金,物业费",
                    "isDeposit": False,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].typeName", "物业费")
            .assert_equal("body.content[0].theoryAmount", 15.5)
            .assert_equal("body.content[0].payedAmount", 15.5)
            .assert_equal("body.content[0].primeAmount", 15.5)
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].typeName", "租金")
            .assert_equal("body.content[1].theoryAmount", 200)
            .assert_equal("body.content[1].payedAmount", 100)
            .assert_equal("body.content[1].primeAmount", 200)
            .assert_equal("body.content[2].action", "IN")
            .assert_equal("body.content[2].typeName", "租金")
            .assert_equal("body.content[2].theoryAmount", 3041.67)
            .assert_equal("body.content[2].payedAmount", 0)
            .assert_equal("body.content[2].primeAmount", 3041.67)
        ),
        Step(
            RunRequest("收缴率详情--按月查询-8")
            .get("${ENV(api_url)}/v2/bills/list")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "page": "0",
                    "payDateFrom": "2021-08-01",
                    "payDateTo": "2021-08-31",
                    "size": "100",
                    "isDeposit": False,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].typeName", "租金")
            .assert_equal("body.content[0].theoryAmount", 98.12)
            .assert_equal("body.content[0].payedAmount", 0)
            .assert_equal("body.content[0].primeAmount", 3041.67)
        ),
        Step(
            RunRequest("收缴率详情--按月查询-9")
            .get("${ENV(api_url)}/v2/bills/list")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "page": "0",
                    "payDateFrom": "2021-09-01",
                    "payDateTo": "2021-09-30",
                    "size": "100",
                    "isDeposit": False,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].typeName", "物业费")
            .assert_equal("body.content[0].theoryAmount", 15.5)
            .assert_equal("body.content[0].payedAmount", 15.5)
            .assert_equal("body.content[0].primeAmount", 15.5)
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].typeName", "租金")
            .assert_equal("body.content[1].theoryAmount", 200)
            .assert_equal("body.content[1].payedAmount", 100)
            .assert_equal("body.content[1].primeAmount", 200)
            .assert_equal("body.content[2].action", "IN")
            .assert_equal("body.content[2].typeName", "租金")
            .assert_equal("body.content[2].theoryAmount", 3041.67)
            .assert_equal("body.content[2].payedAmount", 0)
            .assert_equal("body.content[2].primeAmount", 3041.67)
        ),
        Step(
            RunRequest("收缴率详情--租金、按季查询")
            .get("${ENV(api_url)}/v2/bills/list")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "page": "0",
                    "payDateFrom": "2021-07-01",
                    "payDateTo": "2021-09-30",
                    "size": "100",
                    "isDeposit": False,
                    "type": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].typeName", "租金")
            .assert_equal("body.content[0].theoryAmount", 200)
            .assert_equal("body.content[0].payedAmount", 100)
            .assert_equal("body.content[0].primeAmount", 200)
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].typeName", "租金")
            .assert_equal("body.content[1].theoryAmount", 98.12)
            .assert_equal("body.content[1].payedAmount", 0)
            .assert_equal("body.content[1].primeAmount", 3041.67)
            .assert_equal("body.content[2].action", "IN")
            .assert_equal("body.content[2].typeName", "租金")
            .assert_equal("body.content[2].theoryAmount", 3041.67)
            .assert_equal("body.content[2].payedAmount", 0)
            .assert_equal("body.content[2].primeAmount", 3041.67)
        ),
        Step(
            RunRequest("收缴率详情--租金+物业费、按季查询")
            .get("${ENV(api_url)}/v2/bills/list")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "page": "0",
                    "payDateFrom": "2021-07-01",
                    "payDateTo": "2021-09-30",
                    "size": "100",
                    "isDeposit": False,
                    "type": "租金,物业费",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].typeName", "物业费")
            .assert_equal("body.content[0].theoryAmount", 15.5)
            .assert_equal("body.content[0].payedAmount", 15.5)
            .assert_equal("body.content[0].primeAmount", 15.5)
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].typeName", "租金")
            .assert_equal("body.content[1].theoryAmount", 200)
            .assert_equal("body.content[1].payedAmount", 100)
            .assert_equal("body.content[1].primeAmount", 200)
            .assert_equal("body.content[2].action", "IN")
            .assert_equal("body.content[2].typeName", "租金")
            .assert_equal("body.content[2].theoryAmount", 98.12)
            .assert_equal("body.content[2].payedAmount", 0)
            .assert_equal("body.content[2].primeAmount", 3041.67)
            .assert_equal("body.content[3].action", "IN")
            .assert_equal("body.content[3].typeName", "租金")
            .assert_equal("body.content[3].theoryAmount", 3041.67)
            .assert_equal("body.content[3].payedAmount", 0)
            .assert_equal("body.content[3].primeAmount", 3041.67)
        ),
        Step(
            RunRequest("收缴率详情--按季查询")
            .get("${ENV(api_url)}/v2/bills/list")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "page": "0",
                    "payDateFrom": "2021-07-01",
                    "payDateTo": "2021-09-30",
                    "size": "100",
                    "isDeposit": False,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].typeName", "物业费")
            .assert_equal("body.content[0].theoryAmount", 15.5)
            .assert_equal("body.content[0].payedAmount", 15.5)
            .assert_equal("body.content[0].primeAmount", 15.5)
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].typeName", "租金")
            .assert_equal("body.content[1].theoryAmount", 200)
            .assert_equal("body.content[1].payedAmount", 100)
            .assert_equal("body.content[1].primeAmount", 200)
            .assert_equal("body.content[2].action", "IN")
            .assert_equal("body.content[2].typeName", "租金")
            .assert_equal("body.content[2].theoryAmount", 98.12)
            .assert_equal("body.content[2].payedAmount", 0)
            .assert_equal("body.content[2].primeAmount", 3041.67)
            .assert_equal("body.content[3].action", "IN")
            .assert_equal("body.content[3].typeName", "租金")
            .assert_equal("body.content[3].theoryAmount", 3041.67)
            .assert_equal("body.content[3].payedAmount", 0)
            .assert_equal("body.content[3].primeAmount", 3041.67)
        ),
        Step(
            RunRequest("收缴率详情--租金、按年查询")
            .get("${ENV(api_url)}/v2/bills/list")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "page": "0",
                    "payDateFrom": "2021-01-01",
                    "payDateTo": "2021-12-31",
                    "size": "100",
                    "isDeposit": False,
                    "type": "租金",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].typeName", "租金")
            .assert_equal("body.content[0].theoryAmount", 200)
            .assert_equal("body.content[0].payedAmount", 100)
            .assert_equal("body.content[0].primeAmount", 200)
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].typeName", "租金")
            .assert_equal("body.content[1].theoryAmount", 98.12)
            .assert_equal("body.content[1].payedAmount", 0)
            .assert_equal("body.content[1].primeAmount", 3041.67)
            .assert_equal("body.content[2].action", "IN")
            .assert_equal("body.content[2].typeName", "租金")
            .assert_equal("body.content[2].theoryAmount", 3041.67)
            .assert_equal("body.content[2].payedAmount", 0)
            .assert_equal("body.content[2].primeAmount", 3041.67)
        ),
        Step(
            RunRequest("收缴率详情--租金+物业费、按年查询")
            .get("${ENV(api_url)}/v2/bills/list")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "page": "0",
                    "payDateFrom": "2021-01-01",
                    "payDateTo": "2021-12-31",
                    "size": "100",
                    "isDeposit": False,
                    "type": "租金,物业费",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].typeName", "物业费")
            .assert_equal("body.content[0].theoryAmount", 15.5)
            .assert_equal("body.content[0].payedAmount", 15.5)
            .assert_equal("body.content[0].primeAmount", 15.5)
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].typeName", "租金")
            .assert_equal("body.content[1].theoryAmount", 200)
            .assert_equal("body.content[1].payedAmount", 100)
            .assert_equal("body.content[1].primeAmount", 200)
            .assert_equal("body.content[2].action", "IN")
            .assert_equal("body.content[2].typeName", "租金")
            .assert_equal("body.content[2].theoryAmount", 98.12)
            .assert_equal("body.content[2].payedAmount", 0)
            .assert_equal("body.content[2].primeAmount", 3041.67)
            .assert_equal("body.content[3].action", "IN")
            .assert_equal("body.content[3].typeName", "租金")
            .assert_equal("body.content[3].theoryAmount", 3041.67)
            .assert_equal("body.content[3].payedAmount", 0)
            .assert_equal("body.content[3].primeAmount", 3041.67)
        ),
        Step(
            RunRequest("收缴率详情--按年查询")
            .get("${ENV(api_url)}/v2/bills/list")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "page": "0",
                    "payDateFrom": "2021-01-01",
                    "payDateTo": "2021-12-31",
                    "size": "100",
                    "isDeposit": False,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.content[0].action", "IN")
            .assert_equal("body.content[0].typeName", "物业费")
            .assert_equal("body.content[0].theoryAmount", 15.5)
            .assert_equal("body.content[0].payedAmount", 15.5)
            .assert_equal("body.content[0].primeAmount", 15.5)
            .assert_equal("body.content[1].action", "IN")
            .assert_equal("body.content[1].typeName", "租金")
            .assert_equal("body.content[1].theoryAmount", 200)
            .assert_equal("body.content[1].payedAmount", 100)
            .assert_equal("body.content[1].primeAmount", 200)
            .assert_equal("body.content[2].action", "IN")
            .assert_equal("body.content[2].typeName", "租金")
            .assert_equal("body.content[2].theoryAmount", 98.12)
            .assert_equal("body.content[2].payedAmount", 0)
            .assert_equal("body.content[2].primeAmount", 3041.67)
            .assert_equal("body.content[3].action", "IN")
            .assert_equal("body.content[3].typeName", "租金")
            .assert_equal("body.content[3].theoryAmount", 3041.67)
            .assert_equal("body.content[3].payedAmount", 0)
            .assert_equal("body.content[3].primeAmount", 3041.67)
        ),
        Step(
            RunRequest("删除楼宇")
            .delete("${ENV(api_url)}/buildings/$building_id")
            .with_headers(
                **{
                    "authorization": "Bearer $access_token",
                    "content-type": "application/json; charset=utf-8",
                }
            )
            .validate()
            .assert_equal("status_code", 204)
        ),
    ]


if __name__ == "__main__":
    TestCaseCollectionRates().test_start()
