# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Statistics/assets/collection_rates_monthly.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Buildings.buildings_test import TestCaseBuildings as Buildings


class TestCaseCollectionRatesMonthly(HttpRunner):

    config = (
        Config("数据舱--分摊收缴率")
        .variables(
            **{
                "access_token": "${get_token()}",
                "endDate": "2021-12-31",
                "startDate": "2021-01-01",
            }
        )
        .verify(False)
        .export(*["building_id"])
    )

    teststeps = [
        Step(RunTestCase("获取楼宇id").call(Buildings).export(*["building_id"])),
        Step(
            RunRequest("分摊收缴率--按月查询")
            .get("${ENV(api_url)}/assets/collection-rates/monthly")
            .with_params(
                **{
                    "billSelectAmount": "AMOUNT",
                    "buildingIds": "$building_id",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "switchValue": "percentage",
                    "temporalUnit": "MONTH",
                    "billTypes": "租金,物业费",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("分摊收缴率--按季查询")
            .get("${ENV(api_url)}/assets/collection-rates/monthly")
            .with_params(
                **{
                    "billSelectAmount": "AMOUNT",
                    "buildingIds": "$building_id",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "switchValue": "percentage",
                    "temporalUnit": "QUARTER",
                    "billTypes": "租金,物业费",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("分摊收缴率--按年查询")
            .get("${ENV(api_url)}/assets/collection-rates/monthly")
            .with_params(
                **{
                    "billSelectAmount": "AMOUNT",
                    "buildingIds": "$building_id",
                    "endDate": "$endDate",
                    "startDate": "$startDate",
                    "switchValue": "percentage",
                    "temporalUnit": "YEAR",
                    "billTypes": "租金,物业费",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseCollectionRatesMonthly().test_start()
