# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Statistics/assets/income_average_detail.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Buildings.buildings_test import TestCaseBuildings as Buildings


class TestCaseIncomeAverageDetail(HttpRunner):

    config = (
        Config("数据舱-平效/计租均价-查看详情")
        .variables(
            **{
                "month_beginDate": "2021-07-01",
                "month_endDate": "2021-07-31",
                "quarter_beginDate": "2021-07-01",
                "quarter_endDate": "2021-09-30",
                "year_beginDate": "2021-01-01",
                "year_endDate": "2021-12-31",
                "access_token": "${get_token()}",
            }
        )
        .export(*["building_id"])
    )

    teststeps = [
        Step(RunTestCase("获取楼宇id").call(Buildings).export(*["building_id"])),
        Step(
            RunRequest("数据舱-平效/计租均价-房源(房源)-月详情")
            .get("${ENV(api_url)}/assets/income-per-square/detail")
            .with_params(
                **{
                    "billTypes": "租金",
                    "buildingIds": "$building_id",
                    "beginDate": "$month_beginDate",
                    "endDate": "$month_endDate",
                    "page": "0",
                    "size": "100",
                    "statisticSpaceType": "ROOM",
                    "statisticFineness": "ROOM",
                    "temporalUnit": "MONTH",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.size", 100)
        ),
        Step(
            RunRequest("数据舱-平效/计租均价-房源(楼层)-月详情")
            .get("${ENV(api_url)}/assets/income-per-square/detail")
            .with_params(
                **{
                    "billTypes": "租金",
                    "buildingIds": "$building_id",
                    "beginDate": "$month_beginDate",
                    "endDate": "$month_endDate",
                    "page": "0",
                    "size": "100",
                    "statisticSpaceType": "ROOM",
                    "statisticFineness": "FLOOR",
                    "temporalUnit": "MONTH",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.size", 100)
        ),
        Step(
            RunRequest("数据舱-平效/计租均价-工位-月详情")
            .get("${ENV(api_url)}/assets/income-per-square/detail")
            .with_params(
                **{
                    "billTypes": "租金",
                    "buildingIds": "$building_id",
                    "beginDate": "$month_beginDate",
                    "endDate": "$month_endDate",
                    "page": "0",
                    "size": "100",
                    "statisticSpaceType": "CUBICLE",
                    "temporalUnit": "MONTH",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.size", 100)
        ),
        Step(
            RunRequest("数据舱-平效/计租均价-房源(房源)-季详情")
            .get("${ENV(api_url)}/assets/income-per-square/detail")
            .with_params(
                **{
                    "billTypes": "租金",
                    "buildingIds": "$building_id",
                    "beginDate": "$quarter_beginDate",
                    "endDate": "$quarter_endDate",
                    "page": "0",
                    "size": "100",
                    "statisticSpaceType": "ROOM",
                    "statisticFineness": "ROOM",
                    "temporalUnit": "QUARTER",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.size", 100)
        ),
        Step(
            RunRequest("数据舱-平效/计租均价-房源(楼层)-季详情")
            .get("${ENV(api_url)}/assets/income-per-square/detail")
            .with_params(
                **{
                    "billTypes": "租金",
                    "buildingIds": "$building_id",
                    "beginDate": "$quarter_beginDate",
                    "endDate": "$quarter_endDate",
                    "page": "0",
                    "size": "100",
                    "statisticSpaceType": "ROOM",
                    "statisticFineness": "FLOOR",
                    "temporalUnit": "QUARTER",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.size", 100)
        ),
        Step(
            RunRequest("数据舱-平效/计租均价-工位-季详情")
            .get("${ENV(api_url)}/assets/income-per-square/detail")
            .with_params(
                **{
                    "billTypes": "租金",
                    "buildingIds": "$building_id",
                    "beginDate": "$quarter_beginDate",
                    "endDate": "$quarter_endDate",
                    "page": "0",
                    "size": "100",
                    "statisticSpaceType": "CUBICLE",
                    "temporalUnit": "QUARTER",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.size", 100)
        ),
        Step(
            RunRequest("数据舱-平效/计租均价-房源(房源)-年详情")
            .get("${ENV(api_url)}/assets/income-per-square/detail")
            .with_params(
                **{
                    "billTypes": "租金",
                    "buildingIds": "$building_id",
                    "beginDate": "$year_beginDate",
                    "endDate": "$year_endDate",
                    "page": "0",
                    "size": "100",
                    "statisticSpaceType": "ROOM",
                    "statisticFineness": "ROOM",
                    "temporalUnit": "YEAR",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.size", 100)
        ),
        Step(
            RunRequest("数据舱-平效/计租均价-房源(楼层)-年详情")
            .get("${ENV(api_url)}/assets/income-per-square/detail")
            .with_params(
                **{
                    "billTypes": "租金",
                    "buildingIds": "$building_id",
                    "beginDate": "$year_beginDate",
                    "endDate": "$year_endDate",
                    "page": "0",
                    "size": "100",
                    "statisticSpaceType": "ROOM",
                    "statisticFineness": "FLOOR",
                    "temporalUnit": "YEAR",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.size", 100)
        ),
        Step(
            RunRequest("数据舱-平效/计租均价-工位-年详情")
            .get("${ENV(api_url)}/assets/income-per-square/detail")
            .with_params(
                **{
                    "billTypes": "租金",
                    "buildingIds": "$building_id",
                    "beginDate": "$year_beginDate",
                    "endDate": "$year_endDate",
                    "page": "0",
                    "size": "100",
                    "statisticSpaceType": "CUBICLE",
                    "temporalUnit": "YEAR",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.size", 100)
        ),
    ]


if __name__ == "__main__":
    TestCaseIncomeAverageDetail().test_start()
