# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Collection/collection_detail.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseCollectionDetail(HttpRunner):

    config = Config("获取集合列表详情").variables(**{"access_token": "${get_token()}"})

    teststeps = [
        Step(
            RunRequest("集合列表详情---房源")
            .get("${ENV(api_url)}/buildings/portfolios")
            .with_params(
                **{
                    "page": "0",
                    "portfolioType": "COLLECTION",
                    "size": "1000",
                    "statisticSpaceType": "ROOM",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.numberOfManagement", 1600.0)
            .assert_equal("body.totalRoomCount", 10)
            .assert_equal("body.numberOfAvailable", 700.0)
            .assert_equal("body.totalAvailableRoomCount", 5)
        ),
        Step(
            RunRequest("集合列表详情---工位")
            .get("${ENV(api_url)}/buildings/portfolios")
            .with_params(
                **{
                    "page": "0",
                    "portfolioType": "COLLECTION",
                    "size": "1000",
                    "statisticSpaceType": "CUBICLE",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.numberOfManagement", 36)
            .assert_equal("body.totalRoomCount", 7)
            .assert_equal("body.numberOfAvailable", 20)
            .assert_equal("body.totalAvailableRoomCount", 3)
        ),
        Step(
            RunRequest("集合列表详情---房源+工位")
            .get("${ENV(api_url)}/buildings/portfolios")
            .with_params(
                **{
                    "page": "0",
                    "portfolioType": "COLLECTION",
                    "size": "1000",
                    "statisticSpaceType": "ALL",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.numberOfManagement", 1960)
            .assert_equal("body.totalRoomCount", 17)
            .assert_equal("body.numberOfAvailable", 900.0)
            .assert_equal("body.totalAvailableRoomCount", 8)
        ),
    ]


if __name__ == "__main__":
    TestCaseCollectionDetail().test_start()
