# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Collection/collection.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseCollection(HttpRunner):

    config = Config("获取集合列表").variables(**{"access_token": "${get_token()}"})

    teststeps = [
        Step(
            RunRequest("获取集合列表")
            .post("${ENV(api_url)}/buildings/collections/list")
            .with_headers(
                **{
                    "authorization": "Bearer $access_token",
                    "content-type": "application/json; charset=utf-8",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body[0].id", 9269)
            .assert_equal("body[0].name", "龙湖冠寓（奥体）")
            .assert_equal("body[1].id", 9268)
            .assert_equal("body[1].name", "龙湖冠寓")
        ),
    ]


if __name__ == "__main__":
    TestCaseCollection().test_start()
