# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Project/portfolios.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCasePortfolios(HttpRunner):

    config = Config("获取项目列表").variables(**{"access_token": "${get_token()}"})

    teststeps = [
        Step(
            RunRequest("项目列表")
            .with_variables(**{"access_token": "$access_token"})
            .get("${ENV(api_url)}/buildings/portfolios/list")
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.id", 9405)
            .assert_equal("body.name", "龙湖冠寓")
            .assert_equal("body.type", "COMPANY")
            .assert_equal("body.buildings", None)
            .assert_equal("body.queue", 0)
        ),
    ]


if __name__ == "__main__":
    TestCasePortfolios().test_start()
