# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Project/project_detail.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseProjectDetail(HttpRunner):

    config = Config("获取项目详情").variables(**{"access_token": "${get_token()}"})

    teststeps = [
        Step(
            RunRequest("项目列表详情---房源")
            .get("${ENV(api_url)}/buildings/portfolios")
            .with_params(
                **{
                    "page": "0",
                    "portfolioType": "PROJECT",
                    "size": "1000",
                    "statisticSpaceType": "ROOM",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.id", 9405)
            .assert_equal("body.name", "龙湖冠寓")
            .assert_equal("body.type", "COMPANY")
            .assert_equal("body.numberOfManagement", 1360.0)
            .assert_equal("body.portfolioSummaryModels[0].type", "PROJECT")
            .assert_equal("body.totalRoomCount", 7)
            .assert_equal("body.numberOfAvailable", 200.0)
            .assert_equal("body.totalAvailableRoomCount", 2)
        ),
        Step(
            RunRequest("项目列表详情---工位")
            .get("${ENV(api_url)}/buildings/portfolios")
            .with_params(
                **{
                    "page": "0",
                    "portfolioType": "PROJECT",
                    "size": "1000",
                    "statisticSpaceType": "CUBICLE",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.id", 9405)
            .assert_equal("body.name", "龙湖冠寓")
            .assert_equal("body.type", "COMPANY")
            .assert_equal("body.numberOfManagement", 80)
            .assert_equal("body.totalRoomCount", 7)
            .assert_equal("body.numberOfAvailable", 5)
            .assert_equal("body.totalAvailableRoomCount", 1)
        ),
        Step(
            RunRequest("项目列表详情---房源+工位")
            .get("${ENV(api_url)}/buildings/portfolios")
            .with_params(
                **{
                    "page": "0",
                    "portfolioType": "PROJECT",
                    "size": "1000",
                    "statisticSpaceType": "ALL",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.id", 9405)
            .assert_equal("body.name", "龙湖冠寓")
            .assert_equal("body.type", "COMPANY")
            .assert_equal("body.numberOfManagement", 3370)
            .assert_equal("body.totalRoomCount", 14)
            .assert_equal("body.numberOfAvailable", 250)
            .assert_equal("body.totalAvailableRoomCount", 3)
        ),
    ]


if __name__ == "__main__":
    TestCaseProjectDetail().test_start()
