# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Contract/create_contracts.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Auth.user_info_test import TestCaseUserInfo as UserInfo

from testcases.Buildings.buildings_test import TestCaseBuildings as Buildings


class TestCaseCreateContracts(HttpRunner):

    config = (
        Config("新建合同")
        .variables(
            **{
                "access_token": "${get_token()}",
                "areaSize": "${str_to_int(10)}",
                "room_number": "${random_int(101,199)}",
            }
        )
        .verify(False)
        .export(*["room_id", "building_id", "contract_id", "customerId"])
    )

    teststeps = [
        Step(RunTestCase("获取用户id").call(UserInfo).export(*["customerId"])),
        Step(RunTestCase("获取楼宇id").call(Buildings).export(*["building_id"])),
        Step(
            RunRequest("新增可招商房源")
            .post("${ENV(api_url)}/buildings/$building_id/rooms")
            .with_headers(
                **{
                    "accept": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "areaSize": "$areaSize",
                    "buildingId": "$building_id",
                    "cubicleUpdateRequests": [],
                    "floorName": "1",
                    "jsonData": '[{"required":false,"fieldName":"建筑面积","fieldType":"NUMBER","systemField":true},{"required":false,"fieldName":"装修","fieldType":"SINGLE_SELECT","values":["不限","毛坯","简装","精装"],"systemField":true},{"required":false,"fieldName":"预租单价","fieldType":"NUMBER","systemField":true}]',
                    "marketingAvailable": "true",
                    "realAreaSize": "$areaSize",
                    "roomNumber": "$room_number",
                    "spaceType": "ROOM",
                }
            )
            .extract()
            .with_jmespath("body", "room_id")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("生成租金明细")
            .post("${ENV(api_url)}/v2/contracts/pays")
            .with_headers(**{"authorization": "Bearer $access_token"})
            .with_json(
                {
                    "baseTerm": {
                        "areaSize": "$areaSize",
                        "calculateOrder": "AREA_FIRST",
                        "deposit": 1,
                        "depositPayEnumDesc": "租金保证金",
                        "depositUnitEnum": "MONTH",
                        "leaseBeginDate": "${begin_date()}",
                        "leaseEndDate": "${end_date()}",
                        "monetaryUnit": "人民币CNY",
                        "precisionEnum": "RESULT",
                        "signDate": "${begin_date()}",
                        "spaceUnit": "P",
                        "theoryRounded": False,
                        "unitPricePrecision": 2,
                    },
                    "depositIncreasingRates": [],
                    "discounts": [],
                    "increasingRates": [],
                    "leaseTerms": [
                        {
                            "calculateEnum": "MONTH",
                            "dayNumberForYear": 365,
                            "deposit": False,
                            "intervalMonth": 1,
                            "leaseComputeWay": "FIXED_MONEY",
                            "leaseDivideRoleEnum": "NORMAL",
                            "leaseTermType": "RENT",
                            "leaseTermTypeDesc": "租金",
                            "monetaryUnit": "人民币CNY",
                            "payInAdvanceDay": 1,
                            "paymentDateEnum": "WORKDAY",
                            "price": 10,
                            "priceUnitEnum": "D",
                            "termBeginDate": "${begin_date()}",
                            "termEndDate": "${end_date()}",
                        }
                    ],
                }
            )
            .extract()
            .with_jmespath("body[0].theoryPayDate", "theoryPayDate_0")
            .with_jmespath("body[1].theoryPayDate", "theoryPayDate_1")
            .with_jmespath("body[2].theoryPayDate", "theoryPayDate_2")
            .with_jmespath("body[3].theoryPayDate", "theoryPayDate_3")
            .with_jmespath("body[4].theoryPayDate", "theoryPayDate_4")
            .with_jmespath("body[5].theoryPayDate", "theoryPayDate_5")
            .with_jmespath("body[6].theoryPayDate", "theoryPayDate_6")
            .with_jmespath("body[7].theoryPayDate", "theoryPayDate_7")
            .with_jmespath("body[8].theoryPayDate", "theoryPayDate_8")
            .with_jmespath("body[9].theoryPayDate", "theoryPayDate_9")
            .with_jmespath("body[10].theoryPayDate", "theoryPayDate_10")
            .with_jmespath("body[11].theoryPayDate", "theoryPayDate_11")
            .with_jmespath("body[12].theoryPayDate", "theoryPayDate_12")
            .with_jmespath("body[0].startDate", "startDate_0")
            .with_jmespath("body[1].startDate", "startDate_1")
            .with_jmespath("body[2].startDate", "startDate_2")
            .with_jmespath("body[3].startDate", "startDate_3")
            .with_jmespath("body[4].startDate", "startDate_4")
            .with_jmespath("body[5].startDate", "startDate_5")
            .with_jmespath("body[6].startDate", "startDate_6")
            .with_jmespath("body[7].startDate", "startDate_7")
            .with_jmespath("body[8].startDate", "startDate_8")
            .with_jmespath("body[9].startDate", "startDate_9")
            .with_jmespath("body[10].startDate", "startDate_10")
            .with_jmespath("body[11].startDate", "startDate_11")
            .with_jmespath("body[12].startDate", "startDate_12")
            .with_jmespath("body[0].endDate", "endDate_0")
            .with_jmespath("body[1].endDate", "endDate_1")
            .with_jmespath("body[2].endDate", "endDate_2")
            .with_jmespath("body[3].endDate", "endDate_3")
            .with_jmespath("body[4].endDate", "endDate_4")
            .with_jmespath("body[5].endDate", "endDate_5")
            .with_jmespath("body[6].endDate", "endDate_6")
            .with_jmespath("body[7].endDate", "endDate_7")
            .with_jmespath("body[8].endDate", "endDate_8")
            .with_jmespath("body[9].endDate", "endDate_9")
            .with_jmespath("body[10].endDate", "endDate_10")
            .with_jmespath("body[11].endDate", "endDate_11")
            .with_jmespath("body[12].endDate", "endDate_12")
            .with_jmespath("body[0].finalPrice", "finalPrice_0")
            .with_jmespath("body[1].finalPrice", "finalPrice_1")
            .with_jmespath("body[2].finalPrice", "finalPrice_2")
            .with_jmespath("body[3].finalPrice", "finalPrice_3")
            .with_jmespath("body[4].finalPrice", "finalPrice_4")
            .with_jmespath("body[5].finalPrice", "finalPrice_5")
            .with_jmespath("body[6].finalPrice", "finalPrice_6")
            .with_jmespath("body[7].finalPrice", "finalPrice_7")
            .with_jmespath("body[8].finalPrice", "finalPrice_8")
            .with_jmespath("body[9].finalPrice", "finalPrice_9")
            .with_jmespath("body[10].finalPrice", "finalPrice_10")
            .with_jmespath("body[11].finalPrice", "finalPrice_11")
            .with_jmespath("body[12].finalPrice", "finalPrice_12")
            .with_jmespath("body[0].theoryPayMoney", "theoryPayMoney_0")
            .with_jmespath("body[1].theoryPayMoney", "theoryPayMoney_1")
            .with_jmespath("body[2].theoryPayMoney", "theoryPayMoney_2")
            .with_jmespath("body[3].theoryPayMoney", "theoryPayMoney_3")
            .with_jmespath("body[4].theoryPayMoney", "theoryPayMoney_4")
            .with_jmespath("body[5].theoryPayMoney", "theoryPayMoney_5")
            .with_jmespath("body[6].theoryPayMoney", "theoryPayMoney_6")
            .with_jmespath("body[7].theoryPayMoney", "theoryPayMoney_7")
            .with_jmespath("body[8].theoryPayMoney", "theoryPayMoney_8")
            .with_jmespath("body[9].theoryPayMoney", "theoryPayMoney_9")
            .with_jmespath("body[10].theoryPayMoney", "theoryPayMoney_10")
            .with_jmespath("body[11].theoryPayMoney", "theoryPayMoney_11")
            .with_jmespath("body[12].theoryPayMoney", "theoryPayMoney_12")
            .with_jmespath("body[0].payMoney", "payMoney_0")
            .with_jmespath("body[1].payMoney", "payMoney_1")
            .with_jmespath("body[2].payMoney", "payMoney_2")
            .with_jmespath("body[3].payMoney", "payMoney_3")
            .with_jmespath("body[4].payMoney", "payMoney_4")
            .with_jmespath("body[5].payMoney", "payMoney_5")
            .with_jmespath("body[6].payMoney", "payMoney_6")
            .with_jmespath("body[7].payMoney", "payMoney_7")
            .with_jmespath("body[8].payMoney", "payMoney_8")
            .with_jmespath("body[9].payMoney", "payMoney_9")
            .with_jmespath("body[10].payMoney", "payMoney_10")
            .with_jmespath("body[11].payMoney", "payMoney_11")
            .with_jmespath("body[12].payMoney", "payMoney_12")
            .with_jmespath("body[0].commissionStandard", "commissionStandard_0")
            .with_jmespath("body[1].commissionStandard", "commissionStandard_1")
            .with_jmespath("body[2].commissionStandard", "commissionStandard_2")
            .with_jmespath("body[3].commissionStandard", "commissionStandard_3")
            .with_jmespath("body[4].commissionStandard", "commissionStandard_4")
            .with_jmespath("body[5].commissionStandard", "commissionStandard_5")
            .with_jmespath("body[6].commissionStandard", "commissionStandard_6")
            .with_jmespath("body[7].commissionStandard", "commissionStandard_7")
            .with_jmespath("body[8].commissionStandard", "commissionStandard_8")
            .with_jmespath("body[9].commissionStandard", "commissionStandard_9")
            .with_jmespath("body[10].commissionStandard", "commissionStandard_10")
            .with_jmespath("body[11].commissionStandard", "commissionStandard_11")
            .with_jmespath("body[12].commissionStandard", "commissionStandard_12")
            .with_jmespath("body[0].planRentAmount", "planRentAmount_0")
            .with_jmespath("body[1].planRentAmount", "planRentAmount_1")
            .with_jmespath("body[2].planRentAmount", "planRentAmount_2")
            .with_jmespath("body[3].planRentAmount", "planRentAmount_3")
            .with_jmespath("body[4].planRentAmount", "planRentAmount_4")
            .with_jmespath("body[5].planRentAmount", "planRentAmount_5")
            .with_jmespath("body[6].planRentAmount", "planRentAmount_6")
            .with_jmespath("body[7].planRentAmount", "planRentAmount_7")
            .with_jmespath("body[8].planRentAmount", "planRentAmount_8")
            .with_jmespath("body[9].planRentAmount", "planRentAmount_9")
            .with_jmespath("body[10].planRentAmount", "planRentAmount_10")
            .with_jmespath("body[11].planRentAmount", "planRentAmount_11")
            .with_jmespath("body[12].planRentAmount", "planRentAmount_12")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("新建房源合同--按面积计算租金")
            .post("${ENV(api_url)}/v3/contracts?")
            .with_headers(
                **{
                    "authorization": "Bearer $access_token",
                    "content-type": "application/json; charset=utf-8",
                }
            )
            .with_json(
                {
                    "baseTerm": {
                        "areaSize": "$areaSize",
                        "calculateOrder": "AREA_FIRST",
                        "contractNo": "001",
                        "leaseBeginDate": "${begin_date()}",
                        "leaseEndDate": "${end_date()}",
                        "precisionEnum": "RESULT",
                        "signDate": "${begin_date()}",
                        "spaceUnit": "P",
                        "theoryRounded": False,
                        "unitPricePrecision": 2,
                    },
                    "contractNo": "001",
                    "customKeywords": [],
                    "expenseTerms": [
                        {
                            "areaSize": "$areaSize",
                            "buildingType": "OFFICE",
                            "contractExpenseTermName": "租赁条款",
                            "contractPays": [
                                {
                                    "applyDate": None,
                                    "carryAmount": 0,
                                    "carryForwards": [],
                                    "commissionMoney": 0,
                                    "commissionRateModels": None,
                                    "commissionStandard": "$commissionStandard_0",
                                    "payMoney": "$payMoney_0",
                                    "planRentAmount": "$planRentAmount_0",
                                    "startDate": "$startDate_0",
                                    "endDate": "$endDate_0",
                                    "theoryPayDate": "$theoryPayDate_0",
                                    "theoryPayMoney": "$theoryPayMoney_0",
                                    "finalPrice": "$finalPrice_0",
                                    "commissionStatus": "NONE",
                                    "contractId": None,
                                    "contractPayRentCommission": "NORMAL",
                                    "deposit": False,
                                    "generateBills": False,
                                    "id": None,
                                    "increaseNumber": None,
                                    "increaseRateEnum": None,
                                    "key": "I2N6jRVli",
                                    "monetaryUnit": "人民币CNY",
                                    "moneyDiscount": True,
                                    "normalIndex": "1-1",
                                    "payEnum": "RENT",
                                    "payEnumDesc": "租金",
                                    "priceUnitEnum": "D",
                                    "primaryTermIndex": 1,
                                    "tempPayMoney": None,
                                    "termIndex": 1,
                                },
                                {
                                    "applyDate": None,
                                    "carryAmount": 0,
                                    "carryForwards": [],
                                    "commissionMoney": 0,
                                    "commissionRateModels": None,
                                    "commissionStandard": "$commissionStandard_1",
                                    "payMoney": "$payMoney_1",
                                    "planRentAmount": "$planRentAmount_1",
                                    "startDate": "$startDate_1",
                                    "endDate": "$endDate_1",
                                    "theoryPayDate": "$theoryPayDate_1",
                                    "theoryPayMoney": "$theoryPayMoney_1",
                                    "finalPrice": "$finalPrice_1",
                                    "commissionStatus": "NONE",
                                    "contractId": None,
                                    "contractPayRentCommission": "NORMAL",
                                    "deposit": False,
                                    "generateBills": False,
                                    "id": None,
                                    "increaseNumber": None,
                                    "increaseRateEnum": None,
                                    "key": "gH1LTxtjGs",
                                    "monetaryUnit": "人民币CNY",
                                    "moneyDiscount": True,
                                    "normalIndex": "1-2",
                                    "payEnum": "RENT",
                                    "payEnumDesc": "租金",
                                    "priceUnitEnum": "D",
                                    "primaryTermIndex": 2,
                                    "tempPayMoney": None,
                                    "termIndex": 2,
                                },
                                {
                                    "applyDate": None,
                                    "carryAmount": 0,
                                    "carryForwards": [],
                                    "commissionMoney": 0,
                                    "commissionRateModels": None,
                                    "commissionStandard": "$commissionStandard_2",
                                    "payMoney": "$payMoney_2",
                                    "planRentAmount": "$planRentAmount_2",
                                    "startDate": "$startDate_2",
                                    "endDate": "$endDate_2",
                                    "theoryPayDate": "$theoryPayDate_2",
                                    "theoryPayMoney": "$theoryPayMoney_2",
                                    "finalPrice": "$finalPrice_2",
                                    "commissionStatus": "NONE",
                                    "contractId": None,
                                    "contractPayRentCommission": "NORMAL",
                                    "deposit": False,
                                    "generateBills": False,
                                    "id": None,
                                    "increaseNumber": None,
                                    "increaseRateEnum": None,
                                    "key": "jwYXJiL2V6",
                                    "monetaryUnit": "人民币CNY",
                                    "moneyDiscount": True,
                                    "normalIndex": "1-3",
                                    "payEnum": "RENT",
                                    "payEnumDesc": "租金",
                                    "priceUnitEnum": "D",
                                    "primaryTermIndex": 3,
                                    "tempPayMoney": None,
                                    "termIndex": 3,
                                },
                                {
                                    "applyDate": None,
                                    "carryAmount": 0,
                                    "carryForwards": [],
                                    "commissionMoney": 0,
                                    "commissionRateModels": None,
                                    "commissionStandard": "$commissionStandard_3",
                                    "payMoney": "$payMoney_3",
                                    "planRentAmount": "$planRentAmount_3",
                                    "startDate": "$startDate_3",
                                    "endDate": "$endDate_3",
                                    "theoryPayDate": "$theoryPayDate_3",
                                    "theoryPayMoney": "$theoryPayMoney_3",
                                    "finalPrice": "$finalPrice_3",
                                    "commissionStatus": "NONE",
                                    "contractId": None,
                                    "contractPayRentCommission": "NORMAL",
                                    "deposit": False,
                                    "generateBills": False,
                                    "id": None,
                                    "increaseNumber": None,
                                    "increaseRateEnum": None,
                                    "key": "drF-WA9m8J",
                                    "monetaryUnit": "人民币CNY",
                                    "moneyDiscount": True,
                                    "normalIndex": "1-4",
                                    "payEnum": "RENT",
                                    "payEnumDesc": "租金",
                                    "priceUnitEnum": "D",
                                    "primaryTermIndex": 4,
                                    "tempPayMoney": None,
                                    "termIndex": 4,
                                },
                                {
                                    "applyDate": None,
                                    "carryAmount": 0,
                                    "carryForwards": [],
                                    "commissionMoney": 0,
                                    "commissionRateModels": None,
                                    "commissionStandard": "$commissionStandard_4",
                                    "payMoney": "$payMoney_4",
                                    "planRentAmount": "$planRentAmount_4",
                                    "startDate": "$startDate_4",
                                    "endDate": "$endDate_4",
                                    "theoryPayDate": "$theoryPayDate_4",
                                    "theoryPayMoney": "$theoryPayMoney_4",
                                    "finalPrice": "$finalPrice_4",
                                    "commissionStatus": "NONE",
                                    "contractId": None,
                                    "contractPayRentCommission": "NORMAL",
                                    "deposit": False,
                                    "generateBills": False,
                                    "id": None,
                                    "increaseNumber": None,
                                    "increaseRateEnum": None,
                                    "key": "V6sxwlOyIX",
                                    "monetaryUnit": "人民币CNY",
                                    "moneyDiscount": True,
                                    "normalIndex": "1-5",
                                    "payEnum": "RENT",
                                    "payEnumDesc": "租金",
                                    "priceUnitEnum": "D",
                                    "primaryTermIndex": 5,
                                    "tempPayMoney": None,
                                    "termIndex": 5,
                                },
                                {
                                    "applyDate": None,
                                    "carryAmount": 0,
                                    "carryForwards": [],
                                    "commissionMoney": 0,
                                    "commissionRateModels": None,
                                    "commissionStandard": "$commissionStandard_5",
                                    "payMoney": "$payMoney_5",
                                    "planRentAmount": "$planRentAmount_5",
                                    "startDate": "$startDate_5",
                                    "endDate": "$endDate_5",
                                    "theoryPayDate": "$theoryPayDate_5",
                                    "theoryPayMoney": "$theoryPayMoney_5",
                                    "finalPrice": "$finalPrice_5",
                                    "commissionStatus": "NONE",
                                    "contractId": None,
                                    "contractPayRentCommission": "NORMAL",
                                    "deposit": False,
                                    "generateBills": False,
                                    "id": None,
                                    "increaseNumber": None,
                                    "increaseRateEnum": None,
                                    "key": "kumgYdAaeu",
                                    "monetaryUnit": "人民币CNY",
                                    "moneyDiscount": True,
                                    "normalIndex": "1-6",
                                    "payEnum": "RENT",
                                    "payEnumDesc": "租金",
                                    "priceUnitEnum": "D",
                                    "primaryTermIndex": 6,
                                    "tempPayMoney": None,
                                    "termIndex": 6,
                                },
                                {
                                    "applyDate": None,
                                    "carryAmount": 0,
                                    "carryForwards": [],
                                    "commissionMoney": 0,
                                    "commissionRateModels": None,
                                    "commissionStandard": "$commissionStandard_6",
                                    "payMoney": "$payMoney_6",
                                    "planRentAmount": "$planRentAmount_6",
                                    "startDate": "$startDate_6",
                                    "endDate": "$endDate_6",
                                    "theoryPayDate": "$theoryPayDate_6",
                                    "theoryPayMoney": "$theoryPayMoney_6",
                                    "finalPrice": "$finalPrice_6",
                                    "commissionStatus": "NONE",
                                    "contractId": None,
                                    "contractPayRentCommission": "NORMAL",
                                    "deposit": False,
                                    "generateBills": False,
                                    "id": None,
                                    "increaseNumber": None,
                                    "increaseRateEnum": None,
                                    "key": "akf6GV31in",
                                    "monetaryUnit": "人民币CNY",
                                    "moneyDiscount": True,
                                    "normalIndex": "1-7",
                                    "payEnum": "RENT",
                                    "payEnumDesc": "租金",
                                    "priceUnitEnum": "D",
                                    "primaryTermIndex": 7,
                                    "tempPayMoney": None,
                                    "termIndex": 7,
                                },
                                {
                                    "applyDate": None,
                                    "carryAmount": 0,
                                    "carryForwards": [],
                                    "commissionMoney": 0,
                                    "commissionRateModels": None,
                                    "commissionStandard": "$commissionStandard_7",
                                    "payMoney": "$payMoney_7",
                                    "planRentAmount": "$planRentAmount_7",
                                    "startDate": "$startDate_7",
                                    "endDate": "$endDate_7",
                                    "theoryPayDate": "$theoryPayDate_7",
                                    "theoryPayMoney": "$theoryPayMoney_7",
                                    "finalPrice": "$finalPrice_7",
                                    "commissionStatus": "NONE",
                                    "contractId": None,
                                    "contractPayRentCommission": "NORMAL",
                                    "deposit": False,
                                    "generateBills": False,
                                    "id": None,
                                    "increaseNumber": None,
                                    "increaseRateEnum": None,
                                    "key": "44mFS_h_bs",
                                    "monetaryUnit": "人民币CNY",
                                    "moneyDiscount": True,
                                    "normalIndex": "1-8",
                                    "payEnum": "RENT",
                                    "payEnumDesc": "租金",
                                    "priceUnitEnum": "D",
                                    "primaryTermIndex": 8,
                                    "tempPayMoney": None,
                                    "termIndex": 8,
                                },
                                {
                                    "applyDate": None,
                                    "carryAmount": 0,
                                    "carryForwards": [],
                                    "commissionMoney": 0,
                                    "commissionRateModels": None,
                                    "commissionStandard": "$commissionStandard_8",
                                    "payMoney": "$payMoney_8",
                                    "planRentAmount": "$planRentAmount_8",
                                    "startDate": "$startDate_8",
                                    "endDate": "$endDate_8",
                                    "theoryPayDate": "$theoryPayDate_8",
                                    "theoryPayMoney": "$theoryPayMoney_8",
                                    "finalPrice": "$finalPrice_8",
                                    "commissionStatus": "NONE",
                                    "contractId": None,
                                    "contractPayRentCommission": "NORMAL",
                                    "deposit": False,
                                    "generateBills": False,
                                    "id": None,
                                    "increaseNumber": None,
                                    "increaseRateEnum": None,
                                    "key": "tPhz_lDCIC",
                                    "monetaryUnit": "人民币CNY",
                                    "moneyDiscount": True,
                                    "normalIndex": "1-9",
                                    "payEnum": "RENT",
                                    "payEnumDesc": "租金",
                                    "priceUnitEnum": "D",
                                    "primaryTermIndex": 9,
                                    "tempPayMoney": None,
                                    "termIndex": 9,
                                },
                                {
                                    "applyDate": None,
                                    "carryAmount": 0,
                                    "carryForwards": [],
                                    "commissionMoney": 0,
                                    "commissionRateModels": None,
                                    "commissionStandard": "$commissionStandard_9",
                                    "payMoney": "$payMoney_9",
                                    "planRentAmount": "$planRentAmount_9",
                                    "startDate": "$startDate_9",
                                    "endDate": "$endDate_9",
                                    "theoryPayDate": "$theoryPayDate_9",
                                    "theoryPayMoney": "$theoryPayMoney_9",
                                    "finalPrice": "$finalPrice_9",
                                    "commissionStatus": "NONE",
                                    "contractId": None,
                                    "contractPayRentCommission": "NORMAL",
                                    "deposit": False,
                                    "generateBills": False,
                                    "id": None,
                                    "increaseNumber": None,
                                    "increaseRateEnum": None,
                                    "key": "GyjZDLxeoV",
                                    "monetaryUnit": "人民币CNY",
                                    "moneyDiscount": True,
                                    "normalIndex": "1-10",
                                    "payEnum": "RENT",
                                    "payEnumDesc": "租金",
                                    "priceUnitEnum": "D",
                                    "primaryTermIndex": 10,
                                    "tempPayMoney": None,
                                    "termIndex": 10,
                                },
                                {
                                    "applyDate": None,
                                    "carryAmount": 0,
                                    "carryForwards": [],
                                    "commissionMoney": 0,
                                    "commissionRateModels": None,
                                    "commissionStandard": "$commissionStandard_10",
                                    "payMoney": "$payMoney_10",
                                    "planRentAmount": "$planRentAmount_10",
                                    "startDate": "$startDate_10",
                                    "endDate": "$endDate_10",
                                    "theoryPayDate": "$theoryPayDate_10",
                                    "theoryPayMoney": "$theoryPayMoney_10",
                                    "finalPrice": "$finalPrice_10",
                                    "commissionStatus": "NONE",
                                    "contractId": None,
                                    "contractPayRentCommission": "NORMAL",
                                    "deposit": False,
                                    "generateBills": False,
                                    "id": None,
                                    "increaseNumber": None,
                                    "increaseRateEnum": None,
                                    "key": "46IOGtf5bD",
                                    "monetaryUnit": "人民币CNY",
                                    "moneyDiscount": True,
                                    "normalIndex": "1-11",
                                    "payEnum": "RENT",
                                    "payEnumDesc": "租金",
                                    "priceUnitEnum": "D",
                                    "primaryTermIndex": 11,
                                    "tempPayMoney": None,
                                    "termIndex": 11,
                                },
                                {
                                    "applyDate": None,
                                    "carryAmount": 0,
                                    "carryForwards": [],
                                    "commissionMoney": 0,
                                    "commissionRateModels": None,
                                    "commissionStandard": "$commissionStandard_11",
                                    "payMoney": "$payMoney_11",
                                    "planRentAmount": "$planRentAmount_11",
                                    "startDate": "$startDate_11",
                                    "endDate": "$endDate_11",
                                    "theoryPayDate": "$theoryPayDate_11",
                                    "theoryPayMoney": "$theoryPayMoney_11",
                                    "finalPrice": "$finalPrice_11",
                                    "commissionStatus": "NONE",
                                    "contractId": None,
                                    "contractPayRentCommission": "NORMAL",
                                    "deposit": False,
                                    "generateBills": False,
                                    "id": None,
                                    "increaseNumber": None,
                                    "increaseRateEnum": None,
                                    "key": "62IfbMguRm",
                                    "monetaryUnit": "人民币CNY",
                                    "moneyDiscount": True,
                                    "normalIndex": "1-12",
                                    "payEnum": "RENT",
                                    "payEnumDesc": "租金",
                                    "priceUnitEnum": "D",
                                    "primaryTermIndex": 12,
                                    "tempPayMoney": None,
                                    "termIndex": 12,
                                },
                                {
                                    "applyDate": None,
                                    "carryAmount": 0,
                                    "carryForwards": [],
                                    "commissionMoney": 0,
                                    "commissionRateModels": None,
                                    "commissionStandard": "$commissionStandard_12",
                                    "payMoney": "$payMoney_12",
                                    "planRentAmount": "$planRentAmount_12",
                                    "startDate": "$startDate_12",
                                    "endDate": "$endDate_12",
                                    "theoryPayDate": "$theoryPayDate_12",
                                    "theoryPayMoney": "$theoryPayMoney_12",
                                    "finalPrice": "$finalPrice_12",
                                    "commissionStatus": "NONE",
                                    "contractId": None,
                                    "contractPayRentCommission": "NORMAL",
                                    "deposit": True,
                                    "generateBills": False,
                                    "id": None,
                                    "increaseNumber": None,
                                    "increaseRateEnum": None,
                                    "key": "JS_YnDm8sA",
                                    "monetaryUnit": "人民币CNY",
                                    "moneyDiscount": False,
                                    "normalIndex": None,
                                    "payEnum": "RENT_DEPOSIT",
                                    "payEnumDesc": "租金保证金",
                                    "priceUnitEnum": None,
                                    "primaryTermIndex": None,
                                    "tempPayMoney": None,
                                    "termIndex": 13,
                                },
                            ],
                            "deposit": 1,
                            "depositIncreasingRates": [],
                            "depositUnitEnum": "MONTH",
                            "discounts": [],
                            "expenseTermType": "RENT_TERM",
                            "increasingRates": [],
                            "itemPermission": "RENT_PERMISSION",
                            "leaseTerms": [
                                {
                                    "calculateEnum": "MONTH",
                                    "dayNumberForYear": 365,
                                    "deposit": False,
                                    "intervalMonth": 1,
                                    "leaseComputeWay": "FIXED_MONEY",
                                    "leaseDivideRoleEnum": "NORMAL",
                                    "leaseTermType": "RENT",
                                    "leaseTermTypeDesc": "租金",
                                    "monetaryUnit": "人民币CNY",
                                    "payInAdvanceDay": 1,
                                    "paymentDateEnum": "WORKDAY",
                                    "price": 10,
                                    "priceUnitEnum": "D",
                                    "termBeginDate": "${begin_date()}",
                                    "termEndDate": "${end_date()}",
                                }
                            ],
                            "monetaryUnit": "人民币CNY",
                            "resourceIds": ["$room_id"],
                            "resourceType": "ROOM",
                            "spaceUnit": "P",
                            "termIndex": 1,
                        }
                    ],
                    "followId": 4990,
                    "followName": "13787340624",
                    "jsonData": "[]",
                    "legalPerson": {"name": "李传根"},
                    "remarkTerms": [],
                    "resourceIds": ["$room_id"],
                    "resourceType": "ROOM",
                    "tags": [],
                    "tenantId": 78327,
                    "tenantName": "湖南神雀网络科技有限公司",
                    "tenantNo": None,
                }
            )
            .extract()
            .with_jmespath("body", "contract_id")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("提交合同")
            .post("${ENV(api_url)}/oa/start")
            .with_headers(
                **{
                    "accept": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "buildingIds": ["$building_id"],
                    "subDomainType": "NEW_APPROVAL",
                    "domainType": "CONTRACT",
                    "customerId": "$customerId",
                    "description": "湖南神雀网络科技有限公司/测试楼宇/$room_number",
                    "objectId": "$contract_id",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseCreateContracts().test_start()
