# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Contract/renew_contract.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Buildings.buildings_test import TestCaseBuildings as Buildings


class TestCaseRenewContract(HttpRunner):

    config = (
        Config("续租退租房源合同")
        .variables(
            **{"access_token": "${get_token()}", "areaSize": "${str_to_int(10)}"}
        )
        .verify(False)
        .export(*["room_id", "building_id", "contract_id", "room_number"])
    )

    teststeps = [
        Step(RunTestCase("获取楼宇id").call(Buildings).export(*["building_id"])),
        Step(
            RunRequest("获取合同列表")
            .get("${ENV(api_url)}/v2/contracts")
            .with_params(
                **{
                    "page": 0,
                    "size": 10,
                    "archived": False,
                    "buildingIds": "$building_id",
                    "customFieldFilter": "[]",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .extract()
            .with_jmespath(
                "body.content[?auditStatusName=='已退租'].id|[0]", "contract_id"
            )
            .with_jmespath(
                "body.content[?auditStatusName=='已退租'].resources[0].resourceId|[0]",
                "room_id",
            )
            .with_jmespath(
                "body.content[?auditStatusName=='已退租'].resources[0].roomNumber|[0]",
                "room_number",
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("生成续租房源合同租金明细")
            .post("${ENV(api_url)}/v2/contracts/pays")
            .with_headers(**{"authorization": "Bearer $access_token"})
            .with_json(
                {
                    "baseTerm": {
                        "areaSize": "$areaSize",
                        "calculateOrder": "AREA_FIRST",
                        "deposit": 1,
                        "depositPayEnumDesc": "租金保证金",
                        "depositUnitEnum": "MONTH",
                        "leaseBeginDate": "${begin_date_rw()}",
                        "leaseEndDate": "${end_180()}",
                        "monetaryUnit": "人民币CNY",
                        "precisionEnum": "RESULT",
                        "signDate": "${begin_date()}",
                        "spaceUnit": "P",
                        "theoryRounded": False,
                        "unitPricePrecision": 2,
                    },
                    "depositIncreasingRates": [],
                    "discounts": [],
                    "increasingRates": [],
                    "leaseTerms": [
                        {
                            "calculateEnum": "MONTH",
                            "dayNumberForYear": 365,
                            "deposit": False,
                            "intervalMonth": 1,
                            "leaseComputeWay": "FIXED_MONEY",
                            "leaseDivideRoleEnum": "NORMAL",
                            "leaseTermType": "RENT",
                            "leaseTermTypeDesc": "租金",
                            "monetaryUnit": "人民币CNY",
                            "payInAdvanceDay": 1,
                            "paymentDateEnum": "WORKDAY",
                            "price": 10,
                            "priceUnitEnum": "D",
                            "termBeginDate": "${begin_date_rw()}",
                            "termEndDate": "${end_180()}",
                        }
                    ],
                }
            )
            .extract()
            .with_jmespath("body[0].theoryPayDate", "theoryPayDate_0")
            .with_jmespath("body[1].theoryPayDate", "theoryPayDate_1")
            .with_jmespath("body[2].theoryPayDate", "theoryPayDate_2")
            .with_jmespath("body[3].theoryPayDate", "theoryPayDate_3")
            .with_jmespath("body[4].theoryPayDate", "theoryPayDate_4")
            .with_jmespath("body[5].theoryPayDate", "theoryPayDate_5")
            .with_jmespath("body[6].theoryPayDate", "theoryPayDate_6")
            .with_jmespath("body[0].startDate", "startDate_0")
            .with_jmespath("body[1].startDate", "startDate_1")
            .with_jmespath("body[2].startDate", "startDate_2")
            .with_jmespath("body[3].startDate", "startDate_3")
            .with_jmespath("body[4].startDate", "startDate_4")
            .with_jmespath("body[5].startDate", "startDate_5")
            .with_jmespath("body[6].startDate", "startDate_6")
            .with_jmespath("body[0].endDate", "endDate_0")
            .with_jmespath("body[1].endDate", "endDate_1")
            .with_jmespath("body[2].endDate", "endDate_2")
            .with_jmespath("body[3].endDate", "endDate_3")
            .with_jmespath("body[4].endDate", "endDate_4")
            .with_jmespath("body[5].endDate", "endDate_5")
            .with_jmespath("body[6].endDate", "endDate_6")
            .with_jmespath("body[0].finalPrice", "finalPrice_0")
            .with_jmespath("body[1].finalPrice", "finalPrice_1")
            .with_jmespath("body[2].finalPrice", "finalPrice_2")
            .with_jmespath("body[3].finalPrice", "finalPrice_3")
            .with_jmespath("body[4].finalPrice", "finalPrice_4")
            .with_jmespath("body[5].finalPrice", "finalPrice_5")
            .with_jmespath("body[6].finalPrice", "finalPrice_6")
            .with_jmespath("body[0].theoryPayMoney", "theoryPayMoney_0")
            .with_jmespath("body[1].theoryPayMoney", "theoryPayMoney_1")
            .with_jmespath("body[2].theoryPayMoney", "theoryPayMoney_2")
            .with_jmespath("body[3].theoryPayMoney", "theoryPayMoney_3")
            .with_jmespath("body[4].theoryPayMoney", "theoryPayMoney_4")
            .with_jmespath("body[5].theoryPayMoney", "theoryPayMoney_5")
            .with_jmespath("body[6].theoryPayMoney", "theoryPayMoney_6")
            .with_jmespath("body[0].payMoney", "payMoney_0")
            .with_jmespath("body[1].payMoney", "payMoney_1")
            .with_jmespath("body[2].payMoney", "payMoney_2")
            .with_jmespath("body[3].payMoney", "payMoney_3")
            .with_jmespath("body[4].payMoney", "payMoney_4")
            .with_jmespath("body[5].payMoney", "payMoney_5")
            .with_jmespath("body[6].payMoney", "payMoney_6")
            .with_jmespath("body[0].commissionStandard", "commissionStandard_0")
            .with_jmespath("body[1].commissionStandard", "commissionStandard_1")
            .with_jmespath("body[2].commissionStandard", "commissionStandard_2")
            .with_jmespath("body[3].commissionStandard", "commissionStandard_3")
            .with_jmespath("body[4].commissionStandard", "commissionStandard_4")
            .with_jmespath("body[5].commissionStandard", "commissionStandard_5")
            .with_jmespath("body[6].commissionStandard", "commissionStandard_6")
            .with_jmespath("body[0].planRentAmount", "planRentAmount_0")
            .with_jmespath("body[1].planRentAmount", "planRentAmount_1")
            .with_jmespath("body[2].planRentAmount", "planRentAmount_2")
            .with_jmespath("body[3].planRentAmount", "planRentAmount_3")
            .with_jmespath("body[4].planRentAmount", "planRentAmount_4")
            .with_jmespath("body[5].planRentAmount", "planRentAmount_5")
            .with_jmespath("body[6].planRentAmount", "planRentAmount_6")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("计算退租协议所需金额")
            .get("${ENV(api_url)}/v3/contracts/$contract_id/termination/finance/term")
            .with_params(**{"terminationDate": "${end_date()}"})
            .with_headers(**{"authorization": "Bearer $access_token"})
            .teardown_hook("${wait($response,1)}")
            .extract()
            .with_jmespath("body.rentals[0].billId", "billId_0")
            .with_jmespath("body.rentals[0].curRemainingAmount", "curRemainingAmount_0")
            .with_jmespath("body.rentals[0].expenseTermId", "expenseTermId_0")
            .with_jmespath("body.rentals[0].endDate", "t_endDate_0")
            .with_jmespath("body.rentals[0].endDate", "t_startDate_0")
            .with_jmespath("body.rentals[0].payDate", "t_payDate_0")
            .with_jmespath("body.rentals[0].primeAmount", "primeAmount_0")
            .with_jmespath("body.rentals[0].remainingAmount", "remainingAmount_0")
            .with_jmespath("body.rentals[0].settledStatus", "settledStatus_0")
            .with_jmespath(
                "body.rentals[0].tempCurRemainingAmount", "tempCurRemainingAmount_0"
            )
            .with_jmespath("body.rentals[0].theoryAmount", "theoryAmount_0")
            .with_jmespath("body.rentals[0].diffAmount", "diffAmount_0")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("续租已退租合同")
            .post("${ENV(api_url)}/v3/contracts/renew")
            .with_params(**{"id": "$contract_id"})
            .with_headers(**{"authorization": "Bearer $access_token"})
            .with_json(
                {
                    "newContract": {
                        "baseTerm": {
                            "areaSize": "$areaSize",
                            "calculateOrder": "AREA_FIRST",
                            "contractLeaseDateRule": "DEFAULT",
                            "contractNo": "001",
                            "leaseBeginDate": "${begin_date_rw()}",
                            "leaseEndDate": "${end_180()}",
                            "precisionEnum": "RESULT",
                            "signDate": "${begin_date()}",
                            "spaceUnit": "P",
                            "theoryRounded": False,
                            "unitPricePrecision": 2,
                        },
                        "contractNo": "001",
                        "customKeywords": [],
                        "expenseTerms": [
                            {
                                "areaSize": "$areaSize",
                                "buildingType": "OFFICE",
                                "contractExpenseTermName": "租赁条款",
                                "contractPays": [
                                    {
                                        "applyDate": None,
                                        "carryAmount": 0,
                                        "carryForwards": [],
                                        "commissionMoney": 0,
                                        "commissionRateModels": None,
                                        "commissionStandard": "$commissionStandard_0",
                                        "payMoney": "$payMoney_0",
                                        "planRentAmount": "$planRentAmount_0",
                                        "startDate": "$startDate_0",
                                        "endDate": "$endDate_0",
                                        "theoryPayDate": "$theoryPayDate_0",
                                        "theoryPayMoney": "$theoryPayMoney_0",
                                        "finalPrice": "$finalPrice_0",
                                        "commissionStatus": "NONE",
                                        "contractId": None,
                                        "contractPayRentCommission": "NORMAL",
                                        "deposit": False,
                                        "generateBills": False,
                                        "id": None,
                                        "increaseNumber": None,
                                        "increaseRateEnum": None,
                                        "key": "QTW_lyJlO",
                                        "monetaryUnit": "人民币CNY",
                                        "moneyDiscount": True,
                                        "normalIndex": "1-1",
                                        "payEnum": "RENT",
                                        "payEnumDesc": "租金",
                                        "priceUnitEnum": "D",
                                        "primaryTermIndex": 1,
                                        "tempPayMoney": None,
                                        "termIndex": 1,
                                    },
                                    {
                                        "applyDate": None,
                                        "carryAmount": 0,
                                        "carryForwards": [],
                                        "commissionMoney": 0,
                                        "commissionRateModels": None,
                                        "commissionStandard": "$commissionStandard_1",
                                        "payMoney": "$payMoney_1",
                                        "planRentAmount": "$planRentAmount_1",
                                        "startDate": "$startDate_1",
                                        "endDate": "$endDate_1",
                                        "theoryPayDate": "$theoryPayDate_1",
                                        "theoryPayMoney": "$theoryPayMoney_1",
                                        "finalPrice": "$finalPrice_1",
                                        "commissionStatus": "NONE",
                                        "contractId": None,
                                        "contractPayRentCommission": "NORMAL",
                                        "deposit": False,
                                        "generateBills": False,
                                        "id": None,
                                        "increaseNumber": None,
                                        "increaseRateEnum": None,
                                        "key": "FpYUeSU0x4",
                                        "monetaryUnit": "人民币CNY",
                                        "moneyDiscount": True,
                                        "normalIndex": "1-2",
                                        "payEnum": "RENT",
                                        "payEnumDesc": "租金",
                                        "priceUnitEnum": "D",
                                        "primaryTermIndex": 2,
                                        "tempPayMoney": None,
                                        "termIndex": 2,
                                    },
                                    {
                                        "applyDate": None,
                                        "carryAmount": 0,
                                        "carryForwards": [],
                                        "commissionMoney": 0,
                                        "commissionRateModels": None,
                                        "commissionStandard": "$commissionStandard_2",
                                        "payMoney": "$payMoney_2",
                                        "planRentAmount": "$planRentAmount_2",
                                        "startDate": "$startDate_2",
                                        "endDate": "$endDate_2",
                                        "theoryPayDate": "$theoryPayDate_2",
                                        "theoryPayMoney": "$theoryPayMoney_2",
                                        "finalPrice": "$finalPrice_2",
                                        "commissionStatus": "NONE",
                                        "contractId": None,
                                        "contractPayRentCommission": "NORMAL",
                                        "deposit": False,
                                        "generateBills": False,
                                        "id": None,
                                        "increaseNumber": None,
                                        "increaseRateEnum": None,
                                        "key": "Y5tYzG6bfx",
                                        "monetaryUnit": "人民币CNY",
                                        "moneyDiscount": True,
                                        "normalIndex": "1-3",
                                        "payEnum": "RENT",
                                        "payEnumDesc": "租金",
                                        "priceUnitEnum": "D",
                                        "primaryTermIndex": 3,
                                        "tempPayMoney": None,
                                        "termIndex": 3,
                                    },
                                    {
                                        "applyDate": None,
                                        "carryAmount": 0,
                                        "carryForwards": [],
                                        "commissionMoney": 0,
                                        "commissionRateModels": None,
                                        "commissionStandard": "$commissionStandard_3",
                                        "payMoney": "$payMoney_3",
                                        "planRentAmount": "$planRentAmount_3",
                                        "startDate": "$startDate_3",
                                        "endDate": "$endDate_3",
                                        "theoryPayDate": "$theoryPayDate_3",
                                        "theoryPayMoney": "$theoryPayMoney_3",
                                        "finalPrice": "$finalPrice_3",
                                        "commissionStatus": "NONE",
                                        "contractId": None,
                                        "contractPayRentCommission": "NORMAL",
                                        "deposit": False,
                                        "generateBills": False,
                                        "id": None,
                                        "increaseNumber": None,
                                        "increaseRateEnum": None,
                                        "key": "PGdpuVGiPb",
                                        "monetaryUnit": "人民币CNY",
                                        "moneyDiscount": True,
                                        "normalIndex": "1-4",
                                        "payEnum": "RENT",
                                        "payEnumDesc": "租金",
                                        "priceUnitEnum": "D",
                                        "primaryTermIndex": 4,
                                        "tempPayMoney": None,
                                        "termIndex": 4,
                                    },
                                    {
                                        "applyDate": None,
                                        "carryAmount": 0,
                                        "carryForwards": [],
                                        "commissionMoney": 0,
                                        "commissionRateModels": None,
                                        "commissionStandard": "$commissionStandard_4",
                                        "payMoney": "$payMoney_4",
                                        "planRentAmount": "$planRentAmount_4",
                                        "startDate": "$startDate_4",
                                        "endDate": "$endDate_4",
                                        "theoryPayDate": "$theoryPayDate_4",
                                        "theoryPayMoney": "$theoryPayMoney_4",
                                        "finalPrice": "$finalPrice_4",
                                        "commissionStatus": "NONE",
                                        "contractId": None,
                                        "contractPayRentCommission": "NORMAL",
                                        "deposit": False,
                                        "generateBills": False,
                                        "id": None,
                                        "increaseNumber": None,
                                        "increaseRateEnum": None,
                                        "key": "TlYQbkcWPy",
                                        "monetaryUnit": "人民币CNY",
                                        "moneyDiscount": True,
                                        "normalIndex": "1-5",
                                        "payEnum": "RENT",
                                        "payEnumDesc": "租金",
                                        "priceUnitEnum": "D",
                                        "primaryTermIndex": 5,
                                        "tempPayMoney": None,
                                        "termIndex": 5,
                                    },
                                    {
                                        "applyDate": None,
                                        "carryAmount": 0,
                                        "carryForwards": [],
                                        "commissionMoney": 0,
                                        "commissionRateModels": None,
                                        "commissionStandard": "$commissionStandard_5",
                                        "payMoney": "$payMoney_5",
                                        "planRentAmount": "$planRentAmount_5",
                                        "startDate": "$startDate_5",
                                        "endDate": "$endDate_5",
                                        "theoryPayDate": "$theoryPayDate_5",
                                        "theoryPayMoney": "$theoryPayMoney_5",
                                        "finalPrice": "$finalPrice_5",
                                        "commissionStatus": "NONE",
                                        "contractId": None,
                                        "contractPayRentCommission": "NORMAL",
                                        "deposit": False,
                                        "generateBills": False,
                                        "id": None,
                                        "increaseNumber": None,
                                        "increaseRateEnum": None,
                                        "key": "TlYQbkcWPy",
                                        "monetaryUnit": "人民币CNY",
                                        "moneyDiscount": True,
                                        "normalIndex": "1-6",
                                        "payEnum": "RENT",
                                        "payEnumDesc": "租金",
                                        "priceUnitEnum": "D",
                                        "primaryTermIndex": 6,
                                        "tempPayMoney": None,
                                        "termIndex": 6,
                                    },
                                    {
                                        "applyDate": None,
                                        "carryAmount": 0,
                                        "carryForwards": [],
                                        "commissionMoney": 0,
                                        "commissionRateModels": None,
                                        "commissionStandard": "$commissionStandard_6",
                                        "payMoney": "$payMoney_6",
                                        "planRentAmount": "$planRentAmount_6",
                                        "startDate": "$startDate_6",
                                        "endDate": "$endDate_6",
                                        "theoryPayDate": "$theoryPayDate_6",
                                        "theoryPayMoney": "$theoryPayMoney_6",
                                        "finalPrice": "$finalPrice_6",
                                        "commissionStatus": "NONE",
                                        "contractId": None,
                                        "contractPayRentCommission": "NORMAL",
                                        "deposit": True,
                                        "generateBills": False,
                                        "id": None,
                                        "increaseNumber": None,
                                        "increaseRateEnum": None,
                                        "key": "_4sXeknYKR",
                                        "monetaryUnit": "人民币CNY",
                                        "moneyDiscount": False,
                                        "normalIndex": None,
                                        "payEnum": "RENT_DEPOSIT",
                                        "payEnumDesc": "租金保证金",
                                        "priceUnitEnum": None,
                                        "primaryTermIndex": None,
                                        "tempPayMoney": None,
                                        "termIndex": 7,
                                    },
                                ],
                                "deposit": 1,
                                "depositIncreasingRates": [],
                                "depositUnitEnum": "MONTH",
                                "discounts": [],
                                "expenseTermType": "RENT_TERM",
                                "increasingRates": [],
                                "itemPermission": "RENT_PERMISSION",
                                "leaseTerms": [
                                    {
                                        "calculateEnum": "MONTH",
                                        "dayNumberForYear": 365,
                                        "deposit": False,
                                        "intervalMonth": 1,
                                        "leaseComputeWay": "FIXED_MONEY",
                                        "leaseDivideRoleEnum": "NORMAL",
                                        "leaseTermType": "RENT",
                                        "leaseTermTypeDesc": "租金",
                                        "monetaryUnit": "人民币CNY",
                                        "payInAdvanceDay": 1,
                                        "paymentDateEnum": "WORKDAY",
                                        "price": 10,
                                        "priceUnitEnum": "D",
                                        "termBeginDate": "${begin_date_rw()}",
                                        "termEndDate": "${end_180()}",
                                    }
                                ],
                                "monetaryUnit": "人民币CNY",
                                "resourceIds": ["$room_id"],
                                "resourceType": "ROOM",
                                "spaceUnit": "P",
                                "termIndex": 1,
                            }
                        ],
                        "followId": 4990,
                        "followName": "13787340624",
                        "industryName": None,
                        "jsonData": "[]",
                        "legalPerson": {"name": "李传根"},
                        "remarkTerms": [],
                        "resourceIds": ["$room_id"],
                        "resourceType": "ROOM",
                        "tags": [],
                        "tenantId": 78327,
                        "tenantName": "湖南神雀网络科技有限公司",
                        "tenantNo": None,
                    },
                    "newContractStartDate": "${begin_date_rw()}",
                    "terminationContractCarryForward": {
                        "billList": [
                            {
                                "action": "IN",
                                "adjustAmount": 0,
                                "billId": "$billId_0",
                                "billType": "租金",
                                "carryAmount": None,
                                "carryBills": [],
                                "carryDirectionEnum": None,
                                "curRemainingAmount": "$curRemainingAmount_0",
                                "deposit": False,
                                "diffAmount": "$diffAmount_0",
                                "endDate": "$t_endDate_0",
                                "expenseTermId": "$expenseTermId_0",
                                "historyCarryAmount": 0,
                                "historyCarryBills": [],
                                "historyCarryInAmount": 0,
                                "historyCarryOutAmount": 0,
                                "id": None,
                                "memo": "第1期应收账单",
                                "monetaryUnit": "人民币CNY",
                                "overDueFineAmount": None,
                                "payDate": "$t_payDate_0",
                                "payedAmount": 0,
                                "primeAmount": "$primeAmount_0",
                                "remainingAmount": "$remainingAmount_0",
                                "settledStatus": "$settledStatus_0",
                                "startDate": "$t_startDate_0",
                                "tempCurRemainingAmount": "$tempCurRemainingAmount_0",
                                "theoryAmount": "$theoryAmount_0",
                            }
                        ],
                        "contractId": "$contract_id",
                        "expenseList": [],
                    },
                }
            )
            .teardown_hook("${wait($response,1)}")
            .extract()
            .with_jmespath("body", "contract_newId")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("提交续租已退租合同")
            .setup_hook("${set_contract_sh()}")
            .post("${ENV(api_url)}/oa/start")
            .with_headers(
                **{
                    "content-type": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "buildingIds": ["$building_id"],
                    "subDomainType": "NEW_APPROVAL",
                    "domainType": "CONTRACT",
                    "customerId": 1013,
                    "description": "湖南神雀网络科技有限公司/测试楼宇/$room_number",
                    "objectId": "$contract_newId",
                }
            )
            .teardown_hook("${wait($response,1)}")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("作废已续租合同")
            .post("${ENV(api_url)}/v2/contracts/$contract_newId/nullification")
            .with_params(**{"buildingId": "$building_id"})
            .with_headers(
                **{
                    "content-type": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "memo": "1",
                    "action": "CLOSE_ALL_BILLS",
                    "amortizationScheduleDelete": True,
                }
            )
            .teardown_hook("${wait($response,0.5)}")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("生效作废合同")
            .setup_hook("${set_contract_sh()}")
            .post("${ENV(api_url)}/oa/start")
            .with_headers(
                **{
                    "content-type": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "buildingIds": ["$building_id"],
                    "subDomainType": "NULLIFICATION_APPROVAL",
                    "domainType": "CONTRACT",
                    "customerId": 1013,
                    "description": "湖南神雀网络科技有限公司/测试楼宇/$room_number",
                    "objectId": "$contract_newId",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseRenewContract().test_start()
