# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Contract/renew_contract.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Buildings.buildings_test import TestCaseBuildings as Buildings


class TestCaseRenewContract(HttpRunner):

    config = (
        Config("续租退租房源合同")
        .variables(
            **{"access_token": "${get_token()}", "areaSize": "${str_to_int(10)}"}
        )
        .verify(False)
        .export(*["room_id", "building_id", "contract_id", "room_number"])
    )

    teststeps = [
        Step(RunTestCase("获取楼宇id").call(Buildings).export(*["building_id"])),
        Step(
            RunRequest("获取合同列表")
            .get("${ENV(api_url)}/v2/contracts")
            .with_params(
                **{
                    "page": 0,
                    "size": 10,
                    "archived": False,
                    "buildingIds": "$building_id",
                    "customFieldFilter": "[]",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .extract()
            .with_jmespath(
                "body.content[?auditStatusName=='已退租'].id|[0]", "contract_id"
            )
            .with_jmespath(
                "body.content[?auditStatusName=='已退租'].resources[0].resourceId|[0]",
                "room_id",
            )
            .with_jmespath(
                "body.content[?auditStatusName=='已退租'].resources[0].roomNumber|[0]",
                "room_number",
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("生成续租房源合同租金明细")
            .post("${ENV(api_url)}/v2/contracts/pays")
            .with_headers(**{"authorization": "Bearer $access_token"})
            .with_json(
                {
                    "baseTerm": {
                        "areaSize": "$areaSize",
                        "calculateOrder": "AREA_FIRST",
                        "deposit": 1,
                        "depositPayEnumDesc": "租金保证金",
                        "depositUnitEnum": "MONTH",
                        "leaseBeginDate": "${begin_date_rw()}",
                        "leaseEndDate": "${end_180()}",
                        "monetaryUnit": "人民币CNY",
                        "precisionEnum": "RESULT",
                        "signDate": "${begin_date()}",
                        "spaceUnit": "P",
                        "theoryRounded": False,
                        "unitPricePrecision": 2,
                    },
                    "depositIncreasingRates": [],
                    "discounts": [],
                    "increasingRates": [],
                    "leaseTerms": [
                        {
                            "calculateEnum": "MONTH",
                            "dayNumberForYear": 365,
                            "deposit": False,
                            "intervalMonth": 1,
                            "leaseComputeWay": "FIXED_MONEY",
                            "leaseDivideRoleEnum": "NORMAL",
                            "leaseTermType": "RENT",
                            "leaseTermTypeDesc": "租金",
                            "monetaryUnit": "人民币CNY",
                            "payInAdvanceDay": 1,
                            "paymentDateEnum": "WORKDAY",
                            "price": 10,
                            "priceUnitEnum": "D",
                            "termBeginDate": "${begin_date_rw()}",
                            "termEndDate": "${end_180()}",
                        }
                    ],
                }
            )
            .extract()
            .with_jmespath("body", "contractPays")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("计算退租协议所需金额")
            .get("${ENV(api_url)}/v3/contracts/$contract_id/termination/finance/term")
            .with_params(**{"terminationDate": "${end_date()}"})
            .with_headers(**{"authorization": "Bearer $access_token"})
            .teardown_hook("${wait($response,1)}")
            .extract()
            .with_jmespath("body.rentals", "billList")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("续租已退租合同")
            .post("${ENV(api_url)}/v3/contracts/renew")
            .with_params(**{"id": "$contract_id"})
            .with_headers(**{"authorization": "Bearer $access_token"})
            .with_json(
                {
                    "newContract": {
                        "baseTerm": {
                            "areaSize": "$areaSize",
                            "calculateOrder": "AREA_FIRST",
                            "contractLeaseDateRule": "DEFAULT",
                            "contractNo": "001",
                            "leaseBeginDate": "${begin_date_rw()}",
                            "leaseEndDate": "${end_180()}",
                            "precisionEnum": "RESULT",
                            "signDate": "${begin_date()}",
                            "spaceUnit": "P",
                            "theoryRounded": False,
                            "unitPricePrecision": 2,
                        },
                        "contractNo": "001",
                        "customKeywords": [],
                        "expenseTerms": [
                            {
                                "areaSize": "$areaSize",
                                "buildingType": "OFFICE",
                                "contractExpenseTermName": "租赁条款",
                                "contractPays": "$contractPays",
                                "deposit": 1,
                                "depositIncreasingRates": [],
                                "depositUnitEnum": "MONTH",
                                "discounts": [],
                                "expenseTermType": "RENT_TERM",
                                "increasingRates": [],
                                "itemPermission": "RENT_PERMISSION",
                                "leaseTerms": [
                                    {
                                        "calculateEnum": "MONTH",
                                        "dayNumberForYear": 365,
                                        "deposit": False,
                                        "intervalMonth": 1,
                                        "leaseComputeWay": "FIXED_MONEY",
                                        "leaseDivideRoleEnum": "NORMAL",
                                        "leaseTermType": "RENT",
                                        "leaseTermTypeDesc": "租金",
                                        "monetaryUnit": "人民币CNY",
                                        "payInAdvanceDay": 1,
                                        "paymentDateEnum": "WORKDAY",
                                        "price": 10,
                                        "priceUnitEnum": "D",
                                        "termBeginDate": "${begin_date_rw()}",
                                        "termEndDate": "${end_180()}",
                                    }
                                ],
                                "monetaryUnit": "人民币CNY",
                                "resourceIds": ["$room_id"],
                                "resourceType": "ROOM",
                                "spaceUnit": "P",
                                "termIndex": 1,
                            }
                        ],
                        "followId": 4990,
                        "followName": "13787340624",
                        "industryName": None,
                        "jsonData": "[]",
                        "legalPerson": {"name": "李传根"},
                        "remarkTerms": [],
                        "resourceIds": ["$room_id"],
                        "resourceType": "ROOM",
                        "tags": [],
                        "tenantId": 78327,
                        "tenantName": "湖南神雀网络科技有限公司",
                        "tenantNo": None,
                    },
                    "newContractStartDate": "${begin_date_rw()}",
                    "terminationContractCarryForward": {
                        "billList": "$billList",
                        "contractId": "$contract_id",
                        "expenseList": [],
                    },
                }
            )
            .teardown_hook("${wait($response,1)}")
            .extract()
            .with_jmespath("body", "contract_newId")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("提交续租已退租合同")
            .setup_hook("${set_contract_sh()}")
            .post("${ENV(api_url)}/oa/start")
            .with_headers(
                **{
                    "content-type": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "buildingIds": ["$building_id"],
                    "subDomainType": "NEW_APPROVAL",
                    "domainType": "CONTRACT",
                    "customerId": 1013,
                    "description": "湖南神雀网络科技有限公司/测试楼宇/$room_number",
                    "objectId": "$contract_newId",
                }
            )
            .teardown_hook("${wait($response,1)}")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("作废已续租合同")
            .post("${ENV(api_url)}/v2/contracts/$contract_newId/nullification")
            .with_params(**{"buildingId": "$building_id"})
            .with_headers(
                **{
                    "content-type": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "memo": "1",
                    "action": "CLOSE_ALL_BILLS",
                    "amortizationScheduleDelete": True,
                }
            )
            .teardown_hook("${wait($response,0.5)}")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("生效作废合同")
            .setup_hook("${set_contract_sh()}")
            .post("${ENV(api_url)}/oa/start")
            .with_headers(
                **{
                    "content-type": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "buildingIds": ["$building_id"],
                    "subDomainType": "NULLIFICATION_APPROVAL",
                    "domainType": "CONTRACT",
                    "customerId": 1013,
                    "description": "湖南神雀网络科技有限公司/测试楼宇/$room_number",
                    "objectId": "$contract_newId",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseRenewContract().test_start()
