# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Statistics/rental/contract_follow_detail.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Buildings.buildings_test import TestCaseBuildings as Buildings


class TestCaseContractFollowDetail(HttpRunner):

    config = (
        Config("数据舱--合同跟进分布详情")
        .variables(**{"access_token": "${get_token()}"})
        .export(*["building_id"])
    )

    teststeps = [
        Step(RunTestCase("获取楼宇id").call(Buildings).export(*["building_id"])),
        Step(
            RunRequest("合同跟进分布详情--房源")
            .get(
                "${ENV(api_url)}/data-statistics/rent-analyze/contract/follow-distribution/detail"
            )
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "follow": "测试1",
                    "page": "0",
                    "size": "20",
                    "statisticSpaceType": "ROOM",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("合同跟进分布详情--工位")
            .get(
                "${ENV(api_url)}/data-statistics/rent-analyze/contract/follow-distribution/detail"
            )
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "follow": "测试1",
                    "page": "0",
                    "size": "20",
                    "statisticSpaceType": "CUBICLE",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("合同跟进分布详情--房源+工位")
            .get(
                "${ENV(api_url)}/data-statistics/rent-analyze/contract/follow-distribution/detail"
            )
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "follow": "测试1",
                    "page": "0",
                    "size": "20",
                    "statisticSpaceType": "ALL",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseContractFollowDetail().test_start()
