# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Statistics/rental/contract_follow.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Buildings.buildings_test import TestCaseBuildings as Buildings


class TestCaseContractFollow(HttpRunner):

    config = (
        Config("数据舱--合同跟进分布")
        .variables(**{"access_token": "${get_token()}"})
        .export(*["building_id"])
    )

    teststeps = [
        Step(RunTestCase("获取楼宇id").call(Buildings).export(*["building_id"])),
        Step(
            RunRequest("合同跟进分布--房源--房源面积")
            .get("${ENV(api_url)}/data-statistics/rent-analyze/contract/follow")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "statisticSpaceType": "ROOM",
                    "statisticsType": "AREA_SIZE",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("合同跟进分布--工位--房源工位")
            .get("${ENV(api_url)}/data-statistics/rent-analyze/contract/follow")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "statisticSpaceType": "CUBICLE",
                    "statisticsType": "AREA_SIZE",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("合同跟进分布--房源+工位--房源面积")
            .get("${ENV(api_url)}/data-statistics/rent-analyze/contract/follow")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "statisticSpaceType": "ALL",
                    "statisticsType": "AREA_SIZE",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("合同跟进分布--房源--合同数")
            .get("${ENV(api_url)}/data-statistics/rent-analyze/contract/follow")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "statisticSpaceType": "ROOM",
                    "statisticsType": "CONTRACT_COUNT",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("合同跟进分布--工位--合同数")
            .get("${ENV(api_url)}/data-statistics/rent-analyze/contract/follow")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "statisticSpaceType": "CUBICLE",
                    "statisticsType": "CONTRACT_COUNT",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("合同跟进分布--房源+工位--合同数")
            .get("${ENV(api_url)}/data-statistics/rent-analyze/contract/follow")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "statisticSpaceType": "ALL",
                    "statisticsType": "CONTRACT_COUNT",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseContractFollow().test_start()
