# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Statistics/rental/deal_trend_detail.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Buildings.buildings_test import TestCaseBuildings as Buildings


class TestCaseDealTrendDetail(HttpRunner):

    config = (
        Config("数据舱--成交走势详情")
        .variables(**{"year": "2021", "access_token": "${get_token()}"})
        .export(*["building_id"])
    )

    teststeps = [
        Step(RunTestCase("获取楼宇id").call(Buildings).export(*["building_id"])),
        Step(
            RunRequest("成交走势详情--房源面积--房源")
            .get("${ENV(api_url)}/data-statistics/rent-analyze/deal-trend/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "month": "7",
                    "page": "0",
                    "size": "100",
                    "statisticSpaceType": "ROOM",
                    "statisticsType": "AREA_SIZE",
                    "year": "$year",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("成交走势详情--合同数--房源")
            .get("${ENV(api_url)}/data-statistics/rent-analyze/deal-trend/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "month": "7",
                    "page": "0",
                    "size": "100",
                    "statisticSpaceType": "ROOM",
                    "statisticsType": "CONTRACT_COUNT",
                    "year": "$year",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("成交走势详情--房源工位--工位")
            .get("${ENV(api_url)}/data-statistics/rent-analyze/deal-trend/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "month": "7",
                    "page": "0",
                    "size": "100",
                    "statisticSpaceType": "CUBICLE",
                    "statisticsType": "AREA_SIZE",
                    "year": "$year",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("成交走势详情--合同数--工位")
            .get("${ENV(api_url)}/data-statistics/rent-analyze/deal-trend/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "month": "7",
                    "page": "0",
                    "size": "100",
                    "statisticSpaceType": "CUBICLE",
                    "statisticsType": "CONTRACT_COUNT",
                    "year": "$year",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("成交走势详情--房源面积--房源+工位")
            .get("${ENV(api_url)}/data-statistics/rent-analyze/deal-trend/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "month": "7",
                    "page": "0",
                    "size": "100",
                    "statisticSpaceType": "ALL",
                    "statisticsType": "AREA_SIZE",
                    "year": "$year",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("成交走势详情--合同数--房源+工位")
            .get("${ENV(api_url)}/data-statistics/rent-analyze/deal-trend/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "month": "7",
                    "page": "0",
                    "size": "100",
                    "statisticSpaceType": "ALL",
                    "statisticsType": "CONTRACT_COUNT",
                    "year": "$year",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseDealTrendDetail().test_start()
