# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Statistics/rental/rent_price_detail.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Buildings.buildings_test import TestCaseBuildings as Buildings


class TestCaseRentPriceDetail(HttpRunner):

    config = (
        Config("数据舱--租金实时单价分布详情")
        .variables(**{"access_token": "${get_token()}"})
        .export(*["building_id"])
    )

    teststeps = [
        Step(RunTestCase("获取楼宇id").call(Buildings).export(*["building_id"])),
        Step(
            RunRequest("租金实时单价分布详情--房源--房源面积--元/m²∙天")
            .get("${ENV(api_url)}/data-statistics/rent-analyze/rent-price/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "page": "0",
                    "price": "2.00",
                    "priceUnit": "D",
                    "size": "100",
                    "statisticSpaceType": "ROOM",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("租金实时单价分布详情--工位--房源工位--元/月")
            .get("${ENV(api_url)}/data-statistics/rent-analyze/rent-price/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "page": "0",
                    "price": "2.00",
                    "priceUnit": "YM",
                    "size": "100",
                    "statisticSpaceType": "CUBICLE",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("租金实时单价分布详情--房源+工位--房源面积--元/m²∙天")
            .get("${ENV(api_url)}/data-statistics/rent-analyze/rent-price/detail")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "page": "0",
                    "price": "2.00",
                    "priceUnit": "D",
                    "size": "100",
                    "statisticSpaceType": "ALL",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseRentPriceDetail().test_start()
