# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Account/create_bills.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.Buildings.buildings_test import TestCaseBuildings as Buildings


class TestCaseCreateBills(HttpRunner):

    config = (
        Config("添加账单收入、支出数据")
        .variables(**{"access_token": "${get_token()}"})
        .verify(False)
        .export(*["building_id", "room_id"])
    )

    teststeps = [
        Step(RunTestCase("获取楼宇id").call(Buildings).export(*["building_id"])),
        Step(
            RunRequest("创建房源")
            .post("${ENV(api_url)}/buildings/$building_id/rooms")
            .with_headers(
                **{
                    "accept": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "areaSize": 100,
                    "buildingId": "$building_id",
                    "cubicleUpdateRequests": [],
                    "floorName": "1",
                    "jsonData": '[{"required":false,"fieldName":"建筑面积","fieldType":"NUMBER","systemField":true},{"required":false,"fieldName":"装修","fieldType":"SINGLE_SELECT","values":["不限","毛坯","简装","精装"],"systemField":true},{"required":false,"fieldName":"预租单价","fieldType":"NUMBER","systemField":true}]',
                    "marketingAvailable": "true",
                    "realAreaSize": 100,
                    "roomNumber": 101,
                    "spaceType": "ROOM",
                }
            )
            .teardown_hook("${wait(1)}")
            .extract()
            .with_jmespath("body", "room_id")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("生成房源合同租金明细")
            .post("${ENV(api_url)}/v2/contracts/pays")
            .with_headers(**{"authorization": "Bearer $access_token"})
            .with_json(
                {
                    "baseTerm": {
                        "areaSize": 100,
                        "calculateOrder": "AREA_FIRST",
                        "deposit": 1,
                        "depositPayEnumDesc": "租金保证金",
                        "depositUnitEnum": "MONTH",
                        "leaseBeginDate": "2021-09-01",
                        "leaseEndDate": "2021-09-30",
                        "monetaryUnit": "人民币CNY",
                        "precisionEnum": "RESULT",
                        "signDate": "2021-09-01",
                        "spaceUnit": "P",
                        "theoryRounded": False,
                        "unitPricePrecision": 2,
                    },
                    "depositIncreasingRates": [],
                    "discounts": [],
                    "increasingRates": [],
                    "leaseTerms": [
                        {
                            "calculateEnum": "MONTH",
                            "dayNumberForYear": 365,
                            "deposit": False,
                            "intervalMonth": 1,
                            "leaseComputeWay": "FIXED_MONEY",
                            "leaseDivideRoleEnum": "NORMAL",
                            "leaseTermType": "RENT",
                            "leaseTermTypeDesc": "租金",
                            "monetaryUnit": "人民币CNY",
                            "payInAdvanceDay": 1,
                            "paymentDateEnum": "WORKDAY",
                            "price": 1,
                            "priceUnitEnum": "D",
                            "termBeginDate": "2021-09-01",
                            "termEndDate": "2021-09-30",
                        }
                    ],
                }
            )
            .extract()
            .with_jmespath("body", "contractPays")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("新建房源合同--按面积计算租金(不付款)")
            .post("${ENV(api_url)}/v3/contracts?")
            .with_headers(
                **{
                    "authorization": "Bearer $access_token",
                    "content-type": "application/json; charset=utf-8",
                }
            )
            .with_json(
                {
                    "baseTerm": {
                        "areaSize": 100,
                        "calculateOrder": "AREA_FIRST",
                        "contractNo": "001",
                        "leaseBeginDate": "2021-09-01",
                        "leaseEndDate": "2021-09-30",
                        "precisionEnum": "RESULT",
                        "signDate": "2021-09-01",
                        "spaceUnit": "P",
                        "theoryRounded": False,
                        "unitPricePrecision": 2,
                    },
                    "contractNo": "001",
                    "customKeywords": [],
                    "expenseTerms": [
                        {
                            "areaSize": 100,
                            "buildingType": "OFFICE",
                            "contractExpenseTermName": "租赁条款",
                            "contractPays": "$contractPays",
                            "deposit": 1,
                            "depositIncreasingRates": [],
                            "depositUnitEnum": "MONTH",
                            "discounts": [],
                            "expenseTermType": "RENT_TERM",
                            "increasingRates": [],
                            "itemPermission": "RENT_PERMISSION",
                            "leaseTerms": [
                                {
                                    "calculateEnum": "MONTH",
                                    "dayNumberForYear": 365,
                                    "deposit": False,
                                    "intervalMonth": 1,
                                    "leaseComputeWay": "FIXED_MONEY",
                                    "leaseDivideRoleEnum": "NORMAL",
                                    "leaseTermType": "RENT",
                                    "leaseTermTypeDesc": "租金",
                                    "monetaryUnit": "人民币CNY",
                                    "payInAdvanceDay": 1,
                                    "paymentDateEnum": "WORKDAY",
                                    "price": 1,
                                    "priceUnitEnum": "D",
                                    "termBeginDate": "2021-09-01",
                                    "termEndDate": "2021-09-30",
                                }
                            ],
                            "monetaryUnit": "人民币CNY",
                            "resourceIds": ["$room_id"],
                            "resourceType": "ROOM",
                            "spaceUnit": "P",
                            "termIndex": 1,
                        }
                    ],
                    "followId": 4990,
                    "followName": "13787340624",
                    "jsonData": "[]",
                    "legalPerson": {"name": "李传根"},
                    "remarkTerms": [],
                    "resourceIds": ["$room_id"],
                    "resourceType": "ROOM",
                    "tags": [],
                    "tenantId": 78327,
                    "tenantName": "湖南神雀网络科技有限公司",
                    "tenantNo": None,
                }
            )
            .extract()
            .with_jmespath("body", "contract_id")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("提交合同")
            .setup_hook("${set_contract_sh()}")
            .post("${ENV(api_url)}/oa/start")
            .with_headers(
                **{
                    "accept": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "buildingIds": ["$building_id"],
                    "subDomainType": "NEW_APPROVAL",
                    "domainType": "CONTRACT",
                    "customerId": 1013,
                    "description": "湖南神雀网络科技有限公司/测试楼宇/101",
                    "objectId": "$contract_id",
                }
            )
            .teardown_hook("${wait(1)}")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("创建房源")
            .post("${ENV(api_url)}/buildings/$building_id/rooms")
            .with_headers(
                **{
                    "accept": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "areaSize": 100,
                    "buildingId": "$building_id",
                    "cubicleUpdateRequests": [],
                    "floorName": "1",
                    "jsonData": '[{"required":false,"fieldName":"建筑面积","fieldType":"NUMBER","systemField":true},{"required":false,"fieldName":"装修","fieldType":"SINGLE_SELECT","values":["不限","毛坯","简装","精装"],"systemField":true},{"required":false,"fieldName":"预租单价","fieldType":"NUMBER","systemField":true}]',
                    "marketingAvailable": "true",
                    "realAreaSize": 100,
                    "roomNumber": 102,
                    "spaceType": "ROOM",
                }
            )
            .teardown_hook("${wait(1)}")
            .extract()
            .with_jmespath("body", "room_id_1")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("生成房源合同租金明细")
            .post("${ENV(api_url)}/v2/contracts/pays")
            .with_headers(**{"authorization": "Bearer $access_token"})
            .with_json(
                {
                    "baseTerm": {
                        "areaSize": 100,
                        "calculateOrder": "AREA_FIRST",
                        "deposit": 1,
                        "depositPayEnumDesc": "租金保证金",
                        "depositUnitEnum": "MONTH",
                        "leaseBeginDate": "2021-08-01",
                        "leaseEndDate": "2021-08-31",
                        "monetaryUnit": "人民币CNY",
                        "precisionEnum": "RESULT",
                        "signDate": "2021-08-01",
                        "spaceUnit": "P",
                        "theoryRounded": False,
                        "unitPricePrecision": 2,
                    },
                    "depositIncreasingRates": [],
                    "discounts": [],
                    "increasingRates": [],
                    "leaseTerms": [
                        {
                            "calculateEnum": "MONTH",
                            "dayNumberForYear": 365,
                            "deposit": False,
                            "intervalMonth": 1,
                            "leaseComputeWay": "FIXED_MONEY",
                            "leaseDivideRoleEnum": "NORMAL",
                            "leaseTermType": "RENT",
                            "leaseTermTypeDesc": "租金",
                            "monetaryUnit": "人民币CNY",
                            "payInAdvanceDay": 1,
                            "paymentDateEnum": "WORKDAY",
                            "price": 1,
                            "priceUnitEnum": "D",
                            "termBeginDate": "2021-08-01",
                            "termEndDate": "2021-08-31",
                        }
                    ],
                }
            )
            .extract()
            .with_jmespath("body", "contractPays_1")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("新建房源合同--按面积计算租金(付款并结转)")
            .post("${ENV(api_url)}/v3/contracts?")
            .with_headers(
                **{
                    "authorization": "Bearer $access_token",
                    "content-type": "application/json; charset=utf-8",
                }
            )
            .with_json(
                {
                    "baseTerm": {
                        "areaSize": 100,
                        "calculateOrder": "AREA_FIRST",
                        "contractNo": "001",
                        "leaseBeginDate": "2021-08-01",
                        "leaseEndDate": "2021-08-31",
                        "precisionEnum": "RESULT",
                        "signDate": "2021-08-01",
                        "spaceUnit": "P",
                        "theoryRounded": False,
                        "unitPricePrecision": 2,
                    },
                    "contractNo": "001",
                    "customKeywords": [],
                    "expenseTerms": [
                        {
                            "areaSize": 100,
                            "buildingType": "OFFICE",
                            "contractExpenseTermName": "租赁条款",
                            "contractPays": "$contractPays_1",
                            "deposit": 1,
                            "depositIncreasingRates": [],
                            "depositUnitEnum": "MONTH",
                            "discounts": [],
                            "expenseTermType": "RENT_TERM",
                            "increasingRates": [],
                            "itemPermission": "RENT_PERMISSION",
                            "leaseTerms": [
                                {
                                    "calculateEnum": "MONTH",
                                    "dayNumberForYear": 365,
                                    "deposit": False,
                                    "intervalMonth": 1,
                                    "leaseComputeWay": "FIXED_MONEY",
                                    "leaseDivideRoleEnum": "NORMAL",
                                    "leaseTermType": "RENT",
                                    "leaseTermTypeDesc": "租金",
                                    "monetaryUnit": "人民币CNY",
                                    "payInAdvanceDay": 1,
                                    "paymentDateEnum": "WORKDAY",
                                    "price": 1,
                                    "priceUnitEnum": "D",
                                    "termBeginDate": "2021-08-01",
                                    "termEndDate": "2021-08-31",
                                }
                            ],
                            "monetaryUnit": "人民币CNY",
                            "resourceIds": ["$room_id_1"],
                            "resourceType": "ROOM",
                            "spaceUnit": "P",
                            "termIndex": 1,
                        }
                    ],
                    "followId": 4990,
                    "followName": "13787340624",
                    "jsonData": "[]",
                    "legalPerson": {"name": "李传根"},
                    "remarkTerms": [],
                    "resourceIds": ["$room_id_1"],
                    "resourceType": "ROOM",
                    "tags": [],
                    "tenantId": 78327,
                    "tenantName": "湖南神雀网络科技有限公司",
                    "tenantNo": None,
                }
            )
            .extract()
            .with_jmespath("body", "contract_id_1")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("提交合同")
            .setup_hook("${set_contract_sh()}")
            .post("${ENV(api_url)}/oa/start")
            .with_headers(
                **{
                    "accept": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "buildingIds": ["$building_id"],
                    "subDomainType": "NEW_APPROVAL",
                    "domainType": "CONTRACT",
                    "customerId": 1013,
                    "description": "湖南神雀网络科技有限公司/测试楼宇/102",
                    "objectId": "$contract_id_1",
                }
            )
            .teardown_hook("${wait(2)}")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取需付款合同账单")
            .get("${ENV(api_url)}/v2/bills/list")
            .with_params(
                **{
                    "page": 0,
                    "size": 10,
                    "buildingIds": "$building_id",
                    "payDateFrom": "2021-08-01",
                    "payDateTo": "2021-08-31",
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .extract()
            .with_jmespath("body.content[1].id", "bill_id")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取要匹配流水的事件id")
            .post("${ENV(api_url)}/match/bill-with-cash/default/on-approval")
            .with_headers(**{"authorization": "Bearer $access_token"})
            .with_json({"billIds": ["$bill_id"], "matchDate": "2021-09-15"})
            .extract()
            .with_jmespath("body.objectIds", "objectIds")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("匹配流水生效")
            .setup_hook("${set_contract_sh()}")
            .post("${ENV(api_url)}/oa/start")
            .with_headers(**{"authorization": "Bearer $access_token"})
            .with_json(
                {
                    "buildingIds": ["$building_id"],
                    "customerId": 1013,
                    "description": "批量匹配金额合计3,041.67元",
                    "domainType": "BATCH_CASH_MATCH",
                    "objectIds": "$objectIds",
                    "subDomainType": "NEW_APPROVAL",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("计算退租协议所需金额")
            .get("${ENV(api_url)}/v3/contracts/$contract_id_1/termination/finance/term")
            .with_params(**{"terminationDate": "2021-08-01"})
            .with_headers(**{"authorization": "Bearer $access_token"})
            .extract()
            .with_jmespath("body.rentals[0]", "billList_0")
            .with_jmespath("body.deposits[0]", "billList_1")
            .with_jmespath("body.rentals[0].remainingAmount", "remainingAmount")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("退租房源合同")
            .post("${ENV(api_url)}/v3/contracts/$contract_id_1/termination")
            .with_headers(
                **{
                    "content-type": "application/json; charset=utf-8",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "billList": ["$billList_0", "$billList_1"],
                    "expenseList": [
                        {
                            "costType": "历史账单结算",
                            "diffAmount": "$remainingAmount",
                            "monetaryUnit": "人民币CNY",
                        },
                        {"costType": "其他费用", "diffAmount": 0, "monetaryUnit": "人民币CNY"},
                        {"costType": "保证金", "diffAmount": 0, "monetaryUnit": "人民币CNY"},
                    ],
                    "leaseBeginDate": "2021-08-01",
                    "memo": "",
                    "reasons": ["价格因素"],
                    "registeredAddressModifyEndDate": "2021-08-01",
                    "signDate": "2021-08-01",
                    "tenant": "湖南神雀网络科技有限公司",
                    "terminationDate": "2021-08-01",
                    "virtualId": 827907218296,
                }
            )
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("提交退租合同")
            .setup_hook("${set_contract_sh()}")
            .post("${ENV(api_url)}/oa/start")
            .with_headers(
                **{
                    "content-type": "application/json",
                    "authorization": "Bearer $access_token",
                }
            )
            .with_json(
                {
                    "buildingIds": ["$building_id"],
                    "subDomainType": "TERMINATION_APPROVAL",
                    "domainType": "CONTRACT",
                    "customerId": 1013,
                    "description": "湖南神雀网络科技有限公司/测试楼宇/102",
                    "objectId": "$contract_id_1",
                }
            )
            .teardown_hook("${wait(2)}")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取结转合同账单")
            .get("${ENV(api_url)}/v2/bills/list")
            .with_params(
                **{
                    "buildingIds": "$building_id",
                    "objectId": "$contract_id_1",
                    "closedStatus": "NORMAL",
                    "locked": False,
                    "page": 0,
                    "size": 10000,
                }
            )
            .with_headers(**{"authorization": "Bearer $access_token"})
            .extract()
            .with_jmespath("body.content[1].id", "carryFromId")
            .with_jmespath("body.content[0].id", "carryToId")
            .with_jmespath("body.content[0].availableCarryAmount", "carryAmount")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("发起结转合同账单")
            .post("${ENV(api_url)}/carry-records")
            .with_headers(**{"authorization": "Bearer $access_token"})
            .with_json(
                {
                    "carryDate": "2021-09-15",
                    "carryRecordDetails": [
                        {
                            "carryAmount": "$carryAmount",
                            "carryFromId": "$carryFromId",
                            "carryToId": "$carryToId",
                            "launch": True,
                        },
                        {
                            "carryAmount": "$carryAmount",
                            "carryFromId": "$carryFromId",
                            "carryToId": "$carryToId",
                            "launch": False,
                        },
                    ],
                    "objectId": "$contract_id_1",
                    "objectType": "CONTRACT",
                }
            )
            .extract()
            .with_jmespath("body", "objectId")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("结转合同账单生效")
            .post("${ENV(api_url)}/oa/start")
            .with_headers(**{"authorization": "Bearer $access_token"})
            .with_json(
                {
                    "buildingIds": ["$building_id"],
                    "customerId": 1013,
                    "description": "2021年09月15日/湖南神雀网络科技有限公司",
                    "domainType": "CARRY_FORWARD",
                    "objectId": "$objectId",
                    "subDomainType": "NEW_APPROVAL",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("添加收款账单-租金")
            .post("${ENV(api_url)}/v2/bills")
            .with_headers(
                **{
                    "authorization": "Bearer $access_token",
                    "content-type": "application/json; charset=utf-8",
                }
            )
            .with_json(
                {
                    "billCreateRequest": [
                        {
                            "action": "IN",
                            "amount": 200,
                            "billType": "租金",
                            "buildingIds": ["$building_id"],
                            "deposit": False,
                            "endDate": "2021-09-15",
                            "monetaryUnit": "人民币CNY",
                            "needPayDate": "2021-09-15",
                            "other": "湖南神雀网络科技有限公司",
                            "resourceIds": ["$room_id"],
                            "resourceType": "ROOM",
                            "startDate": "2021-09-01",
                            "tenantId": 78327,
                            "tenantNo": None,
                        }
                    ],
                    "cashCreateRequest": {
                        "action": "IN",
                        "amount": "100",
                        "matchDate": "2021-09-15T11:24:08.611Z",
                        "enterDate": "2021-09-15T11:24:04.655Z",
                        "tenantName": "湖南神雀网络科技",
                        "monetaryUnit": "人民币CNY",
                    },
                    "flag": True,
                }
            )
            .teardown_hook("${wait(1)}")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("添加收款账单-租金保证金")
            .post("${ENV(api_url)}/v2/bills")
            .with_headers(
                **{
                    "authorization": "Bearer $access_token",
                    "content-type": "application/json; charset=utf-8",
                }
            )
            .with_json(
                {
                    "billCreateRequest": [
                        {
                            "action": "IN",
                            "amount": 50,
                            "billType": "租金保证金",
                            "buildingIds": ["$building_id"],
                            "deposit": False,
                            "endDate": "2021-09-15",
                            "monetaryUnit": "人民币CNY",
                            "needPayDate": "2021-09-15",
                            "other": "湖南神雀网络科技有限公司",
                            "resourceIds": ["$room_id"],
                            "resourceType": "ROOM",
                            "startDate": "2021-09-01",
                            "tenantId": 78327,
                            "tenantNo": None,
                        }
                    ],
                    "cashCreateRequest": {
                        "action": "IN",
                        "amount": "50",
                        "matchDate": "2021-09-15T11:24:08.611Z",
                        "enterDate": "2021-09-15T11:24:04.655Z",
                        "tenantName": "湖南神雀网络科技",
                        "monetaryUnit": "人民币CNY",
                    },
                    "flag": True,
                }
            )
            .teardown_hook("${wait(1)}")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("添加收款账单-物业费")
            .post("${ENV(api_url)}/v2/bills")
            .with_headers(
                **{
                    "authorization": "Bearer $access_token",
                    "content-type": "application/json; charset=utf-8",
                }
            )
            .with_json(
                {
                    "billCreateRequest": [
                        {
                            "action": "IN",
                            "amount": 15.5,
                            "billType": "物业费",
                            "buildingIds": ["$building_id"],
                            "deposit": False,
                            "endDate": "2021-09-15",
                            "monetaryUnit": "人民币CNY",
                            "needPayDate": "2021-09-15",
                            "other": "湖南神雀网络科技有限公司",
                            "resourceIds": ["$room_id"],
                            "resourceType": "ROOM",
                            "startDate": "2021-09-01",
                            "tenantId": 78327,
                            "tenantNo": None,
                        }
                    ],
                    "cashCreateRequest": {
                        "action": "IN",
                        "amount": "15.5",
                        "matchDate": "2021-09-15T11:24:08.611Z",
                        "enterDate": "2021-09-15T11:24:04.655Z",
                        "tenantName": "湖南神雀网络科技",
                        "monetaryUnit": "人民币CNY",
                    },
                    "flag": True,
                }
            )
            .teardown_hook("${wait(1)}")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("添加付款账单-租金")
            .post("${ENV(api_url)}/v2/bills")
            .with_headers(
                **{
                    "authorization": "Bearer $access_token",
                    "content-type": "application/json; charset=utf-8",
                }
            )
            .with_json(
                {
                    "billCreateRequest": [
                        {
                            "action": "OUT",
                            "amount": 100,
                            "billType": "租金",
                            "buildingIds": ["$building_id"],
                            "deposit": False,
                            "endDate": "2021-09-15",
                            "monetaryUnit": "人民币CNY",
                            "needPayDate": "2021-09-15",
                            "other": "湖南神雀网络科技有限公司",
                            "resourceIds": ["$room_id"],
                            "resourceType": "ROOM",
                            "startDate": "2021-09-01",
                            "tenantId": 78327,
                            "tenantNo": None,
                        }
                    ],
                    "cashCreateRequest": {
                        "action": "OUT",
                        "amount": "100",
                        "matchDate": "2021-09-15T11:24:08.611Z",
                        "enterDate": "2021-09-15T11:24:04.655Z",
                        "tenantName": "湖南神雀网络科技",
                        "monetaryUnit": "人民币CNY",
                    },
                    "flag": True,
                }
            )
            .teardown_hook("${wait(1)}")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("添加付款账单-租金保证金")
            .post("${ENV(api_url)}/v2/bills")
            .with_headers(
                **{
                    "authorization": "Bearer $access_token",
                    "content-type": "application/json; charset=utf-8",
                }
            )
            .with_json(
                {
                    "billCreateRequest": [
                        {
                            "action": "OUT",
                            "amount": 30,
                            "billType": "租金保证金",
                            "buildingIds": ["$building_id"],
                            "deposit": False,
                            "endDate": "2021-09-15",
                            "monetaryUnit": "人民币CNY",
                            "needPayDate": "2021-09-15",
                            "other": "湖南神雀网络科技有限公司",
                            "resourceIds": ["$room_id"],
                            "resourceType": "ROOM",
                            "startDate": "2021-09-01",
                            "tenantId": 78327,
                            "tenantNo": None,
                        }
                    ],
                    "cashCreateRequest": {
                        "action": "OUT",
                        "amount": "20",
                        "matchDate": "2021-09-15T11:24:08.611Z",
                        "enterDate": "2021-09-15T11:24:04.655Z",
                        "tenantName": "湖南神雀网络科技",
                        "monetaryUnit": "人民币CNY",
                    },
                    "flag": True,
                }
            )
            .teardown_hook("${wait(1)}")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("添加付款账单-物业费")
            .post("${ENV(api_url)}/v2/bills")
            .with_headers(
                **{
                    "authorization": "Bearer $access_token",
                    "content-type": "application/json; charset=utf-8",
                }
            )
            .with_json(
                {
                    "billCreateRequest": [
                        {
                            "action": "OUT",
                            "amount": 35.5,
                            "billType": "物业费",
                            "buildingIds": ["$building_id"],
                            "deposit": False,
                            "endDate": "2021-09-15",
                            "monetaryUnit": "人民币CNY",
                            "needPayDate": "2021-09-15",
                            "other": "湖南神雀网络科技有限公司",
                            "resourceIds": ["$room_id"],
                            "resourceType": "ROOM",
                            "startDate": "2021-09-01",
                            "tenantId": 78327,
                            "tenantNo": None,
                        }
                    ],
                    "cashCreateRequest": {
                        "action": "OUT",
                        "amount": "35.5",
                        "matchDate": "2021-09-15T11:24:08.611Z",
                        "enterDate": "2021-09-15T11:24:04.655Z",
                        "tenantName": "湖南神雀网络科技",
                        "monetaryUnit": "人民币CNY",
                    },
                    "flag": True,
                }
            )
            .teardown_hook("${wait(1)}")
            .validate()
            .assert_equal("status_code", 201)
        ),
    ]


if __name__ == "__main__":
    TestCaseCreateBills().test_start()
