# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/Buildings/buildings.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseBuildings(HttpRunner):

    config = (
        Config("楼宇列表")
        .variables(**{"access_token": "${get_token()}"})
        .export(*["building_id"])
    )

    teststeps = [
        Step(
            RunRequest("楼宇列表信息")
            .get("${ENV(api_url)}/buildings")
            .with_headers(**{"authorization": "Bearer $access_token"})
            .extract()
            .with_jmespath("body.items[0].id", "building_id")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseBuildings().test_start()
